runelite-client/src/main/java/net/runelite/client/rs/ClientConfigLoader.java, runelite-client/src/main/java/net/runelite/client/rs/ClientLoader.java, runelite-client/src/main/java/net/runelite/client/rs/RSAppletStub.java, runelite-client/src/main/java/net/runelite/client/rs/RSConfig.java, runelite-client/src/main/java/net/runelite/client/rs/bytecode/ByteCodePatcher.java, runelite-client/src/main/java/net/runelite/client/rs/bytecode/ByteCodeUtils.java, runelite-client/src/main/java/net/runelite/client/rs/bytecode/Hooks.java, runelite-client/src/main/java/net/runelite/client/rs/bytecode/transformers/ActorTransform.java, runelite-client/src/main/java/net/runelite/client/rs/bytecode/transformers/PlayerTransform.java, runelite-client/src/main/java/net/runelite/client/rs/bytecode/transformers/ProjectileTransform.java, runelite-client/src/main/java/net/runelite/client/rs/bytecode/transformers/getProjectileTransform.java
cleaned up a bit of the imports / code
=> Added getProjectile tranform & zeruths player transform

runelite-client/pom.xml
added org.jetbrains.annotations
=> added org.jetbrains.annotations

whalewatchers/WhaleWatchersConfig.java, whalewatchers/WhaleWatchersGloryOverlay.java, whalewatchers/WhaleWatchersOverlay.java, whalewatchers/WhaleWatchersPlugin.java, whalewatchers/WhaleWatchersProtOverlay.java, whalewatchers/WhaleWatchersSmiteableOverlay.java
=> Whale Watchers plugin

runelite-client/src/main/java/net/runelite/client/plugins/kittennotifier/KittenNotifierConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/kittennotifier/KittenNotifierPlugin.java, runelite-client/src/main/java/net/runelite/client/rs/bytecode/ByteCodePatcher.java, runelite-client/src/main/java/net/runelite/client/rs/bytecode/transformers/ClientTransform.java
Adds all protected menu transforms necessary for blackjacking!
Eat shit upstream :)
Also shuts kitten notifier the fuck up. don't know if it still works though 🤷‍♂️
=> ClientTransform

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
=> Updated raids plugin

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/smelting/SmeltingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/smelting/SmeltingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/smelting/SmeltingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/smelting/SmeltingSession.java
Added smelting plugin
Added hide take to ground items
Added text outline to ground items
=>  Added hide take, text outline to ground items etc

runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/FreezeTimersPlugin.java
=> Check Matcher#find

runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/BarbarianAssaultPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/batools/BAToolsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/equipmentinspector/EquipmentInspectorPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/hydra/HydraPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/lootingbagviewer/LootingBagViewerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/profiles/ProfilesPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/pyramidplunder/PyramidPlunderPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/SuppliesTrackerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/vetion/VetionPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/vorkath/VorkathPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/zulrah/ZulrahPlugin.java
Changed multiple "type" values, and name schemes of certain plugins for better organization and flow.
=> Plugin organization

runelite-client/src/main/java/net/runelite/client/plugins/maxhit/MaxHitPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/worldmaphider/WorldMapHiderPlugin.java
Updated plugins with proper "types" for organization.
=> Plugin type Organization

runelite-client/src/main/resources/net/runelite/client/runelite.properties
Reverts runelite-extended/runelite#65
=> Revert "Change main window title to RuneLitePlus"

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/FriendMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsService.java
Added offline friend canvas / minimap indicators
=> Updated player indicators

runelite-client/src/main/java/net/runelite/client/plugins/safespot/SafeSpotConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/safespot/SafeSpotOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/safespot/SafeSpotPlugin.java
=> 1 way PVP Safespots

runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPanel.java
We aren't code thieves so im trying to make license more visible, and we love the runelite client! So no need to remove patreon link.
Also adds the projects discord link.
=> Adding link to license, and runelites patreon

alchemicalhydra/Hydra.java, alchemicalhydra/HydraOverlay.java, alchemicalhydra/HydraPhase.java, alchemicalhydra/HydraPlugin.java, alchemicalhydra/HydraPoisonOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/profiles/ProfilePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/profiles/ProfilesConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/profiles/ProfilesPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/profiles/ProfilesPlugin.java
=> alchemicalhydra

runelite-client/src/main/java/net/runelite/client/plugins/tarnslair/Obstacles.java, runelite-client/src/main/java/net/runelite/client/plugins/tarnslair/TarnsLairOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/tarnslair/TarnsLairPlugin.java
=> Add Tarn's Lair plugin

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
- Integrated within the Travel config option
- Swap Board to Pay-fare for the travel cart near Hajedy
=> Add: "Pay-fare" to swap "Board" on the Travel Cart

runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsPlugin.java
Status bar toggle when not in combat
=> Status bar toggle when not in combat

runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/BarbarianAssaultPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/musicmodifier/MusicCustomizerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/smelting/SmeltingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/tarnslair/TarnsLairPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/vorkath/VorkathPlugin.java
-Rename Vorkath Helper
-Updated Type for Tarns plugin
-Updated Type for Music plugin
-Added Guzzle override for Rock cake
-Changed Type for Default Runelite Barb Assault plugin
-Updated Type for Smithing plugin
=> Plugin Cleanup and Organization

runelite-client/src/main/java/net/runelite/client/plugins/olmcrippletimer/OlmCrippleTimerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/olmcrippletimer/OlmCrippleTimerPlugin.java
One of the OC from CCClient, some may be added soon.
=> Added olm cripple timer overlay

runelite-client/src/main/java/net/runelite/client/plugins/poison/PoisonInfobox.java, runelite-client/src/main/java/net/runelite/client/plugins/poison/PoisonPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimerTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
yeah, all should've been merged upstream already but you know how things are
=> Loads of poison improvements, and a touch of imbued heart

runelite-client/src/main/java/net/runelite/client/plugins/playerinfo/PlayerInfoConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/playerinfo/PlayerInfoCustomIndicator.java, runelite-client/src/main/java/net/runelite/client/plugins/playerinfo/PlayerInfoPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperConfig.java
=>  Added player info plugin

runelite-client/src/main/java/net/runelite/client/rs/bytecode/transformers/ActorTransform.java
=> Adding Oak's graphic change transformer

runelite-client/pom.xml
(when building artifacts you must extract flexo to the artifact)
=> added flexo to client pom so external plugins using flexo will not crash

runelite-client/src/main/java/net/runelite/client/plugins/spellbook/Spell.java, runelite-client/src/main/java/net/runelite/client/plugins/spellbook/SpellbookConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/spellbook/SpellbookMouseListener.java, runelite-client/src/main/java/net/runelite/client/plugins/spellbook/SpellbookPlugin.java, runelite-client/src/main/scripts/MagicSpellBookRedraw.rs2asm
needs a while to get used to the soft caress of your scrollwheel
=> Add scrollwheel resizing for individual spells

runelite-client/src/main/java/net/runelite/client/plugins/ztob/TheatreConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/ztob/TheatreOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/ztob/TheatrePlugin.java
=> Adding Color-Blind Helper for Sote

runelite-client/src/main/java/net/runelite/client/plugins/runedoku/RunedokuConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runedoku/RunedokuOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runedoku/RunedokuPiece.java, runelite-client/src/main/java/net/runelite/client/plugins/runedoku/RunedokuPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/runedoku/RunedokuUtil.java, runelite-client/src/main/java/net/runelite/client/plugins/runedoku/Sudoku.java
To be included in the Runelite+ package.
=> Runedoku plugin (check https://github.com/gazivodag/runedoku)

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java
=> Removing Broken Function - PlayerIndicators

runelite-client/src/main/java/net/runelite/client/plugins/zulrah/ZulrahConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/zulrah/ZulrahJadOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/zulrah/ZulrahOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/zulrah/ZulrahPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/zulrah/ZulrahTileOverlay.java
Was missing a few features for some reason.
=> Bringing Zulrah back up to date.

runelite-client/src/main/java/net/runelite/client/plugins/olmprayagainst/OlmPrayAgainstOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/olmprayagainst/OlmPrayAgainstPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/olmprayagainst/PrayAgainst.java
Tells you what to pray on Olm
Credits to gazivodag
=> Adding Olm Pray Against Plugin

runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningPlugin.java
=> Reformat and Update to AoE Warnings

runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsPlugin.java
Yummy yummy yummy implings in my tummy
=> Add dynamic impling spawns. credit to github.com/Juzzed

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
Github loves long ones holy shit
=> Remove GPU debug messages on startup, lets be real we aint fixing that

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilitySession.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/LapCounterOverlay.java
Add toggles for 'Laps to Goal/Level' overlay text
=> Kyleeld agility 1

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java
=> Fix Cannon Notifier Spam

runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeProjectile.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeProjectileInfo.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningPlugin.java
Credits to https://github.com/farhan1666/
=> AoE Warnings now uses CycleCount -farhan1666

runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/slayermusiq/QuestGuideLinks.java, runelite-client/src/main/java/net/runelite/client/plugins/slayermusiq/SlayermusiqPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/tickcounter/TickCounterPlugin.java
- Corrected Mining plugin to proper Plugin type
- Changed Tick counter to PVP from utility for main use
- Added Slayermusiq1 quest helper to the client due to request
=> Plugin organization and addition

runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/FreezeTimersConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/FreezeTimersOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/FreezeTimersPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/PlayerSpellEffect.java, runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/PrayerTracker.java, runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/TimerType.java, runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/Timers.java
Now have the option to only show text.
Blue = TB
White = Barrage
Red = Veng
=> FreezeTimers Added Functionality

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsService.java
PKLite - Resolve "Indicating pile is broken"
=> PKLite - Resolve "Indicating pile is broken"

runelite-client/src/main/java/net/runelite/client/flexo/Flexo.java, runelite-client/src/main/java/net/runelite/client/plugins/flexo/FlexoPlugin.java
=> fix flexo window border offsets

runelite-client/src/main/java/net/runelite/client/plugins/hideprayers/HidePrayersConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/hideprayers/HidePrayersPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/hideprayers/PrayerTabState.java
optional toggles:
rapid heal
rapid restore
steel skin
incredible reflex
redemption
preserve
=> Hide Prayers update

runelite-client/src/main/java/net/runelite/client/plugins/hideprayers/HidePrayersConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/hideprayers/HidePrayersPlugin.java
split out Aug/Rig & Eagle/Mystic
=> split out Aug/Rig & Eagle/Mystic

runelite-client/src/main/java/net/runelite/client/plugins/hideprayers/PVM/HidePrayersPVMConfig.java
-Changed descriptions for new Prayer Hider Config
=> Code cleanup

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsConfig.java
=> Update so Enhanced Scouter Title should always be enabled.

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java
=> centers out clan chat spacing

runelite-client/src/main/java/net/runelite/client/plugins/hideprayers/PVM/HidePrayersPVMConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/hideprayers/PVM/HidePrayersPVMPlugin.java
-Added Vorkath Cheap/Expensive
-Added Cerberus Melee/Range Cheap/Expensive
-Added all GWD Bosses Cheap/Expensive
=> Configurable Boss Updated

runelite-client/src/main/java/net/runelite/client/plugins/prayeralert/PrayerAlertConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/prayeralert/PrayerAlertOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayeralert/PrayerAlertPlugin.java
=> Licence fix

runelite-client/src/main/java/net/runelite/client/plugins/climbupclimbdown/ClimbPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/climbupclimbdown/ShiftCtrlInputListener.java
(interferes with shift walker plugin)
=> climb up climb down plugin using shift and ctrl

runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java
=> Fix commits behind? 

runelite-client/src/main/java/net/runelite/client/plugins/spellbook/SpellbookPlugin.java
Will mess up current spell size, but makes scrolling increment total size by 2 px instead of by 5. Max size is now the total width (184px).
=> Spellbook: Make sure spells are 100% contained in the widget

runelite-client/src/main/java/net/runelite/client/plugins/fightcave/FightCavePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/fightcave/NPCContainer.java, runelite-client/src/main/java/net/runelite/client/plugins/fightcave/TimersOverlay.java
Example of it here
https://streamable.com/zipgc
Please squash :)
=> Fight Caves Update

runelite-client/src/main/java/net/runelite/client/plugins/ammo/AmmoCounter.java
Fixing NPE that was occuring in ammo plugin when you equip arrows/bolts.
=> Fix NPE in Ammo Plugin

runelite-client/src/main/java/net/runelite/client/plugins/spellbook/SpellbookPlugin.java
Last update broke a lot of functionality, this fixes that
=> Spellbook fixes

runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java
May or may not also have 3 extra tabs added in hydra
=> Enable chat filter for game messages as well

cache-client/pom.xml, cache-updater/pom.xml, cache/pom.xml, http-api/pom.xml, http-service/pom.xml, pom.xml, protocol-api/pom.xml, protocol/pom.xml, runelite-api/pom.xml, runelite-client/pom.xml, runelite-mixins/pom.xml, runelite-plugin-archetype/pom.xml, runelite-script-assembler-plugin/pom.xml, runescape-api/pom.xml
Reverts runelite-extended/runelite#261
=> Revert "Merge upstream"

runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/FontStyle.java, runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/FreezeTimersConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/FreezeTimersOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/FreezeTimersPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/PlayerSpellEffect.java, runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/PrayerTracker.java, runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/TimerType.java, runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/Timers.java
Quite a big overhaul on the text timers, also fixes jumping timers.
=> FreezeTimers Text Overhaul

runelite-api/src/main/java/net/runelite/api/Client.java
```java
/**
*
* @param param0 This is SceneX for gameObject, index for items, and 0 for npc.
* @param param1 This is SceneY for gameObject, static for items, and 0 for npc.
* @param type Menu entry Action type.
* @param id Targets ID
* @param menuEntry Do these actually matter?
* @param targetString Do these actually matter?
* @param canvasX Canvas X Point
* @param canvasY Canvas Y Point
*/```
=> Adding correct param identifiers.

runelite-client/src/main/java/net/runelite/client/plugins/easyscape/EasyscapePlugin.java
=> left click eternal glory

runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraPoisonOverlay.java
added a thicker stroke to the outline of the fountain
=> Made Fountains easier to see the outline

runelite-api/src/main/java/net/runelite/api/ProjectileID.java, runelite-client/src/main/java/net/runelite/client/plugins/zcox/CoxPlugin.java
added OLM_MAGE_ATTACK and OLM_RANGE_ATTACK ids
=> Added COX Olm attacking projectile IDs

runelite-client/src/main/java/net/runelite/client/plugins/raids/shortcuts/ShortcutOverlay.java
=> fixed incorrect ID

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsTimer.java
This should fix https://github.com/runelite-extended/runelite/issues/287
Also brings it up to parity with https://github.com/Blackberry0Pie version
=> Update to Raids, fixes timer issue aswell.

runelite-client/src/main/java/net/runelite/client/menus/AbstractMenuEntry.java, runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
Also basically paves the way to make swaps/hides 100% localized in MenuManager. Is way more resource-efficient than the last way of doing this.
=> Improve priority menu entries

runelite-client/src/main/java/net/runelite/client/plugins/entertochat/EnterToChatListener.java, runelite-client/src/main/java/net/runelite/client/plugins/entertochat/EnterToChatPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/wasdcamera/WASDCameraPlugin.java
press enter to chat - no wasd shit
=> press enter to chat - no wasd shit

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/ThreeStepCrypticClue.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/potions/PrayerPotion.java, runelite-client/src/main/java/net/runelite/client/plugins/roguesden/RoguesDenPlugin.java, runelite-client/src/main/java/net/runelite/client/util/ItemUtil.java, runelite-client/src/test/java/net/runelite/client/util/ItemUtilTest.java
Added Added item util
changed some plugins to use item util
=> Added item util, changed some plugins to use item util

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldSwitcherPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldTableRow.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/ping/IPHlpAPI.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/ping/IcmpEchoReply.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/ping/Ping.java
Restore Worldhopper, world history hides the worlds in the default world list, thats annoying so restoring the default plugin.
=> Restore Worldhopper

runelite-client/src/main/java/net/runelite/client/plugins/tmorph/TMorph.java, runelite-client/src/main/java/net/runelite/client/plugins/tmorph/TMorphConfig.java
https://streamable.com/qh6q5
This allows you to morph your items based on config.
THIS IS LOCAL ONLY, other players will not see it.
=> Adding Tmorph Plugin

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsConfig.java
=> Make Scouterer Gooderer Lookinin

http-api/src/main/java/net/runelite/http/api/RuneLiteAPI.java, runelite-client/src/main/java/net/runelite/client/SessionClient.java
Switch to our session endpoint
=> Switch to our session endpoint

runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java
=> Use normalized item ID for osb lookups in examine plugin

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> Nmz swapper

runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java
not sure why this was left in the original pr but it's removed now
=> Removed unnecessary debugging

runelite-client/src/main/java/net/runelite/client/menus/AbstractMenuEntry.java, runelite-client/src/main/java/net/runelite/client/menus/ComparableEntry.java, runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/main/java/net/runelite/client/plugins/easyscape/EasyscapeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/easyscape/EasyscapePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> Yuuuge menu things

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java
Shows "Join playername" instead of "Join" to prevent misclicks
=> shows "Join playername" instead of "Join" to prevent misclicks

runelite-client/src/main/java/net/runelite/client/plugins/tmorph/TMorph.java, runelite-client/src/main/java/net/runelite/client/plugins/tmorph/TMorphConfig.java
Also changes update function to occur on game tick rather than other methods, as its way more reliable.
=> Updated Tmorph to include Anim Swaps

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerOverlay.java
We can interact with objects that far away anyways.
=> Remove overlay draw distance

runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/CoxPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/TimersOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/keptondeath/KeptOnDeathPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/runeliteplus/RuneLitePlusPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/tickcounter/TickCounterOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/tickcounter/TickCounterPlugin.java
Reduced functionality, but stable.
=> Stable -> Master ✓

runelite-client/src/main/java/net/runelite/client/plugins/batools/BAToolsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/equipmentinspector/EquipmentInspectorPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/runedoku/Sudoku.java, runelite-client/src/main/java/net/runelite/client/plugins/stonedloottracker/ui/LootPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/zulrah/phase/ZulrahPhase.java
not sure why println crap was pushed into public release
=> Removed System.out.println debugging

runelite-client/src/main/java/net/runelite/client/rs/ClientLoader.java, runelite-client/src/main/java/net/runelite/client/rs/ClientUpdateCheckMode.java
=> Add custom client updatecheck mode to easily load from file

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPanel.java
=> Fix DC Scouter

runelite-client/src/main/java/net/runelite/client/plugins/banlist/BanListConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/banlist/BanListPlugin.java
=> code cleanup courtesy of ganom

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
Fixes flicker caused by a string option having multiple lines in config. Also changes type checks to use else if's instead of multiple if's
=> config: fixes menu/scrollbar flicker

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPanel.java
https://github.com/runelite-extended/runelite/pull/421 gotta uncomment shit out lol
=> Fix Raids DC Scout

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
May we finally have some rest from the 20 million questions on discord regarding this feature.
<3
=> Construction Swap Fix

runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsOverlay.java
https://github.com/runelite-extended/runelite/issues/383
Hull was one of the only options i could work with. I hope these extra options help!
=> More Obj Indicators Options

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/RuneLiteProperties.java
Usage:
--proxy ip:port:user:pass | ip:port
=> Add CLI SOCKS5 proxy support

runelite-client/pom.xml, runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/plugins/runeliteplus/RuneLitePlusConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runeliteplus/RuneLitePlusPlugin.java, runelite-client/src/main/resources/logback.xml
Add sentry log support to better help log errors and debug track traces etc
=> Add sentry log support

runelite-client/src/main/java/net/runelite/client/plugins/pileindicators/PileIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/pileindicators/PileIndicatorsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/pileindicators/PileIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/pileindicators/PileType.java
Ability to highlight players, NPCS, and both that are stacked on each other. (PvP, chinning, etc.)
Plugin in action:
https://gyazo.com/8461d5188887a476aede1e4471ed7366
=> Pile Indicators plugin

runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/BarbarianAssaultPlugin.java
temporary barbarian assault call timer fix until I finish merging the two barbarian assault plugins
=> barbarian assault: fixes call timer

runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java
Adds an option to hide non-widget tooltips
=> smol change

runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/CoxPlugin.java
Closes https://github.com/runelite-extended/runelite/issues/466
=> Vanguards Fix & Olm Solo TP Fix.

runelite-client/src/main/java/net/runelite/client/plugins/blackjack/BlackjackPlugin.java
thanks again https://github.com/Infinitay
=>  Fix Blackjack Plugin to use menuManager

runelite-client/pom.xml, runelite-client/src/main/java/net/runelite/client/plugins/runeliteplus/RuneLitePlusConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runeliteplus/RuneLitePlusPlugin.java, runelite-client/src/main/resources/logback.xml
Reverts runelite-extended/runelite#454
=> Revert "Add sentry log support"

runelite-client/src/main/java/net/runelite/client/plugins/tmorph/TMorph.java
Fixed morph being on by default and causing issues
=> Fixed morph being on by default and causing issues

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Would've made a global destroy but some things are not as important as these two items
Squash and merge pls and thx
=> Hide "Destroy" options for Rune pouch and Coal bag

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Also added the ability to hide "drop" on runecrafting pouches
Final result:
=> Added more untradeables to the swapper and gave them their own category

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java
=> Add Dev Tools Cursor Pos

runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningPlugin.java
=> AoE notifier

deobfuscator/src/test/java/net/runelite/deob/updater/UpdateMappingsTest.java
don't merge until build passes :P
=> Make travis work again

runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingCounterOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsPlugin.java
=> Add impling overlay

runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoInfobox.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoNPC.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoNibberOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoPlugin.java
=> Added inferno plugin <3

runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoInfobox.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoNPC.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoNibberOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoPlugin.java
changed 'Players' to 'Nibblers'
=> added copyright to inferno

runelite-mixins/src/main/java/net/runelite/mixins/RSSceneMixin.java
i have no idea if this actually even changes how it works but i got asked to pr it
=> Unlimit setTargetTile in RSSceneMixin

runescape-api/src/main/java/net/runelite/rs/api/RSMessage.java
=> Fix message name/prefix import

runelite-api/src/main/java/net/runelite/api/Client.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
isSpellSelected and selectedSpellName getters
=> Spell info hooks

runelite-client/src/main/java/net/runelite/client/plugins/runeliteplus/RuneLitePlusPlugin.java, runescape-client/src/main/java/BoundaryObject.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/FriendSystem.java, runescape-client/src/main/java/OwnWorldComparator.java, runescape-client/src/main/java/WorldMap.java, runescape-client/src/main/java/class54.java
Also a tiny bit of refactoring
=> use Character.isDigit() for bankpin

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/rs/ClientLoader.java
Make both `--localinjected` and `--rs=CUSTOM` work
Make `--rs=VANILLA` work again
=> Update clientloader (and tell only developers to turn on assertions)

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoJadAttack.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoJadOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoWaveDisplayMode.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoWaveMonster.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoWaveOverlay.java
=> More inferno stuff

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/ticktimers/FontStyle.java, runelite-client/src/main/java/net/runelite/client/plugins/ticktimers/NPCContainer.java, runelite-client/src/main/java/net/runelite/client/plugins/ticktimers/TickTimersConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/ticktimers/TickTimersPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/ticktimers/TimersOverlay.java
I plan to expand this plugin to include a variety of bosses that would benefit having accurate tick timings.
This closes https://github.com/runelite-extended/runelite/issues/567
=> Accurate Tick Timers for General Graardor

runelite-client/src/main/java/net/runelite/client/plugins/runeliteplus/RuneLitePlusPlugin.java
=> Check for config on script callbacks for bank pin and make it work with poh/grand exchange

runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/Hydra.java, runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraPhase.java, runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraPlugin.java
=> Revert temporary fixes as they've been permanently fixed

runelite-client/src/main/java/net/runelite/client/plugins/banlist/BanListPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/banlist/ListType.java
seperate wdr lists into scam/toxic, thanks to 99spellign
fix npe issue
=> banlist addition and fixup

runelite-api/src/main/java/net/runelite/api/VarPlayer.java, runelite-client/src/main/java/net/runelite/client/plugins/poison/ActorPoisonInfo.java, runelite-client/src/main/java/net/runelite/client/plugins/poison/PoisonActorOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/poison/PoisonConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/poison/PoisonPlugin.java
https://gfycat.com/EqualThoroughCygnet
=> Add poison tracking for other players/npcs

runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/statusbars/config/BarMode.java, runelite-client/src/main/java/net/runelite/client/plugins/statusbars/renderer/BarRenderer.java, runelite-client/src/main/java/net/runelite/client/plugins/statusbars/renderer/EnergyRenderer.java, runelite-client/src/main/java/net/runelite/client/plugins/statusbars/renderer/HitPointsRenderer.java, runelite-client/src/main/java/net/runelite/client/plugins/statusbars/renderer/PrayerRenderer.java, runelite-client/src/main/java/net/runelite/client/plugins/statusbars/renderer/SpecialAttackRenderer.java
Added changing the left and right side
=> Updated the statusbar

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
fix glory & wealth teleport options
will no longer offer "teleport" if item is uncharged
=> fix glory & wealth teleport options

runelite-client/src/main/java/net/runelite/client/plugins/ticktimers/NPCContainer.java, runelite-client/src/main/java/net/runelite/client/plugins/ticktimers/TickTimersPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/ticktimers/TimersOverlay.java
Cleans up the map usage, no longer have separate maps for each npc.
=> Updated Bosstick timers Plugin - Cleaned up Map Usage

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
wasn't needed, kid who suggested it was retarded
=> Revert "fix glory & wealth teleport options"

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPartyOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
=> Updated Raids Plugin / Add party info display

runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsOverlay.java
[Preview](https://streamable.com/4uir6)
=> Updated Tile Indicator Plugin - Added true current tile

runelite-client/src/main/java/net/runelite/client/plugins/lizardmenshaman/LizardmenShamanPlugin.java
Previously this was using google eventbus rather than runelites own eventbus.
this fixes https://github.com/runelite-extended/runelite/issues/624
=> Fix Lizardmen Shaman

runelite-client/src/main/java/net/runelite/client/plugins/runedoku/RunedokuConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runedoku/RunedokuUtil.java
Added if check for item.getId() to catch -1
Added some licenses
=> Runedoku fix

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> Fix #631 "Swap Puro-Puro Wheat not working"

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderBridgeMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderMixin.java
=> Added NPC hider based on name

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Menu entry shop swapper should now work.
This checks if the option is value and checks if buy/sell is active so both values for buying and selling don't conflict with each other
=> Fix issue #635

runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnaceCofferOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemRecoilOverlay.java
Bug fix for  #641
Some other overlays may be broken from the tables update but here is a fix
=> Bug fix for blastfurnace overlay

runelite-client/src/main/java/net/runelite/client/plugins/raids/Raid.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidRoom.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPartyOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPointsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/shortcuts/ShortcutPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/solver/Layout.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/solver/LayoutSolver.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/solver/RotationSolver.java
This will color good crabs purple and bad crabs red if config setting is enabled.
If you scout a record raid, it will show up as such, and give you a little info in chat.
This closes https://github.com/runelite-extended/runelite/issues/532
=> Add Crab Handlers and Record Raids to Scouter.

runelite-client/src/main/java/net/runelite/client/plugins/blackjack/BlackjackConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/blackjack/BlackjackPlugin.java
isKnockedOut is no longer being used to swap menu entrys. So it was removed
Added other message to trigger knockout tick. This pickpockets the bandit when he aggros you preventing trading damage and better xp/h
=> Blackjack update

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/util/QuestCapeMode.java
added menuManager.removeSwaps("max cape"); to remove swaps.
added questcape for equipment interface
=> Questcape menuentry

runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeProjectile.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningPlugin.java
Obviously this shouldn't be on every projectile that we offer, so i added a filter for them, if i missed any or if you think i should remove one of the current ones just LMK.
On a side note, when I was at Vorkath and he shot out the poison, all them tick counters went off at once, it made me crack up and die a horrible death 😢
=> Accurate Tick Timers for Aoe Warnings

runelite-client/src/main/java/net/runelite/client/plugins/runeliteplus/RuneLitePlusPlugin.java
=> keyboard bank pin for NMZ

injector-plugin/src/main/java/net/runelite/injector/InjectHookMethod.java, runelite-mixins/src/main/java/net/runelite/mixins/ClickboxMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSModelMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSTileMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSUserListMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSModel.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/class238.java, runescape-client/src/main/java/class30.java
=> Fix various injector/mixin issues

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderMixin.java
Closes https://github.com/runelite-extended/runelite/issues/689
=> Entity Hider Mixin NPE Fixin

injected-client/pom.xml, runelite-client/pom.xml, runelite-client/src/main/java/net/runelite/client/rs/ClientLoader.java, runelite-client/src/main/java/net/runelite/client/util/bootstrap/Artifact.java, runelite-client/src/main/java/net/runelite/client/util/bootstrap/Bootstrap.java
Dependant-ish on https://github.com/runelite-extended/maven-repo/pull/26
=> Make injected-client a maven dependency

runelite-client/src/main/java/net/runelite/client/plugins/banlist/BanListPlugin.java
This was causing an issue where toxic players were being labeled as scammers.
Toxic players now colored orange, to indicate caution, and labeled appropriately in trade interface.
=> Add Seperate handler for Toxic Lists

runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoWaveDisplayMode.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoWaveMappings.java, runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoWaveOverlay.java
Pro tip: Hide whitespace changes
=> Cleanup inferno plugin (functionality should be the same)

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
add ninja impling menu entry swapper
=> add ninja impling

runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/Hydra.java, runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraPhase.java, runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraSceneOverlay.java
Add hydra-logic to hydra instead of plugin
Lazy load overlay images and move to enum
Lombok some more
=> Refactor hydra plugin

runelite-client/src/main/java/net/runelite/client/plugins/runedoku/RunedokuConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runedoku/RunedokuOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runedoku/RunedokuUtil.java
Off by default
https://gyazo.com/4493c14558d85b04f093f67ee7cf93cd
https://i.gyazo.com/d3a60c6753e1d234c4e7d8dcc2830825.png
=> Runedoku ability to render only selected rune

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItem.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
=> Added ground item ticks

http-api/src/main/java/net/runelite/http/api/RuneLiteAPI.java
=> Fix HTTP API User-Agent

runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java
Show HA profit while casting HA
=> Show HA profit while casting HA

runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/CoxInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/CoxPlugin.java
add prayer orb msgs if no prayer protection is used 
remove prayer infobox detached position
high priority for infobox
=> cox misc. fixes

runelite-api/src/main/java/net/runelite/api/WorldType.java, runelite-client/src/main/java/net/runelite/client/plugins/hideprayers/HidePrayersPlugin.java
hide prayers now accomodates high risk worlds and will remove protect item as you cant use it.
new worldtypes: Deadman & High Risk
=> hide prayers update + new worldtypes

runelite-client/src/main/java/net/runelite/client/plugins/whalewatchers/WhaleWatchersPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/whalewatchers/WhaleWatchersProtOverlay.java
=> Fixes protect item overlay in pvp worlds

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/solver/Layout.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/solver/LayoutSolver.java
This should improve performance in raids as well, since I removed checking on client tick.
=> Rework scouter Crab Handler & other various misc things.

runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/CoxOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/CoxPlugin.java
=> coxhelper: add olm cripple chat msg for timer to work

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
=> TTL on XP Globes fixes #762

runelite-client/src/main/java/net/runelite/client/plugins/corp/CorpDamageOverlay.java
=> corp revert - fixes #705

runelite-api/src/main/java/net/runelite/api/WorldType.java, runelite-client/src/main/java/net/runelite/client/plugins/hideprayers/HidePrayersConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/hideprayers/HidePrayersPlugin.java
fixes issue with prot item appearing on DMM.
fixes misconception of "hide prayer" when it should be tick to enable prayer.
fixes bug with rapid heal
=> Prayer rework + bug fix

runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
moves majority of `onMenuEntryAdded` code to `onClientTick`
=> menumanager: fix shift drop when shift to walk is enabled

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
tidy up menu entry swapper to make it easier adding config options
added PVM remove cast options when in COX & TOB
=> refactor menu entry swapper

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
fix for tob/cox options, otherwise it hides cast for NPC Too
=> fix for tob/cox options

runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragPlugin.java
Fixes #792 
Disabled by default so it won't affect anything unless someone specifically enables it.
=> Adds an "Always on" antidrag option

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/CombatIconsOverlay.java
Set the font to bold because it's hard to read with other fonts
=> Change font on boosts overlay

runelite-client/src/main/java/net/runelite/client/plugins/shiftwalker/ShiftWalkerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/shiftwalker/ShiftWalkerPlugin.java
Adds the option to let you loot with the shift to walk plugin.
=> Shift Looting

runelite-api/src/main/java/net/runelite/api/events/NpcCompositionChanged.java, runelite-mixins/src/main/java/net/runelite/mixins/RSNPCMixin.java
Thanks to owain for throwing this my way.
=> Add NPC Composition Changed Event

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> fixes some bugs with menu entry swapper

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/util/DigsitePendantMode.java
=> Fixes #834, Digsite Pendant swap option not working

runelite-client/src/main/java/net/runelite/client/plugins/theatre/RoomHandler.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/TheatreConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/TheatreConstant.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/TheatreOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/TheatrePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/TheatreRoom.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/BloatHandler.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/MaidenHandler.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/Nylos.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/SotetsegHandler.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/VerzikHandler.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/nylocas/NyloHandler.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/nylocas/NyloOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/nylocas/NyloPredictor.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/xarpus/XarpusCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/xarpus/XarpusHandler.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/timers/RoomTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/timers/Timeable.java
Added Nylo Helper to Maiden...
Holy fuck, What in the ever living fuck is this monstrosity of a plugin. I'm actually terrified to re-work this one. Literally 6 different plugins in one, this should not of been merged in this state.
https://streamable.com/cqm02
=> theatre: added nylo helper to maiden, and various tob code style fixes.

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
This does not fix some bugs, but adds a ton more. Make sure you're testing these changes in the live client before merging.
=> Revert "fixes some bugs with menu entry swapper"

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/TargetClickboxOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/TargetMinimapOverlay.java
Fixes highlighting at Kraken, Cerb, other NPCs that change composition
Closes #557
=> Use NpcCompositionChanged in SlayerPlugin

runelite-mixins/src/main/java/net/runelite/mixins/RSNPCMixin.java
=> Fixed npc despawn event

runelite-api/src/main/java/net/runelite/api/events/NpcDefinitionChanged.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/TheatrePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/MaidenHandler.java, runelite-mixins/src/main/java/net/runelite/mixins/RSNPCMixin.java
Also added it to maiden handler to remove nylos on definitonchanged.
=> refactor: npcomp to npcdef to stay consistent with mixin naming.

runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneOverlay.java
resolves points overlay not showing
confirmed working with @Justin
=> NMZ points overlay not showing fix

runelite-client/src/main/java/net/runelite/client/plugins/corp/CorpDamageOverlay.java
update corp overlay to follow new table building practice
=> Corp Overlay update

runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneOverlay.java
NMZ total points added as config option
breaks sammich otherwise =[
=> NMZ total points added as config option

runelite-client/src/main/java/net/runelite/client/plugins/lootingbagviewer/LootingBagViewerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/lootingbagviewer/LootingBagViewerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/lootingbagviewer/LootingBagViewerWidgetOverlay.java
Ability to see GP amount overlayed on looting bag
Config
There is no varbit to consistently check the looting bags value... but there is plenty of clever ideas I've come up with that are TODO's within the plugin's code!
Everybody's welcome to make changes.
=> lootingbagviewer: add gp amount overlay to looting bag in inventory.

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
fixes 853, and part of 805, also a number of reported discord bugs.
added in the correct swaps & missing target.equals evaluation points.
added TOB + COX to PVM group type.
=> menuentryswapper: various fixes

runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RunepouchOverlay.java
bring inline with font manager
currently ignores font manager
=> incorporate font manager into rune pouch

runelite-client/src/main/java/net/runelite/client/plugins/runeliteplus/RuneLitePlusPlugin.java
**Added:**
- Seed Vault
- Miscellania
- STASH Units
- Bond Pouch
- Tool Leprechaun
=> Added several missing interfaces to bank pin plugin

runelite-client/src/main/java/net/runelite/client/menus/ComparableEntry.java, runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/main/java/net/runelite/client/plugins/shiftwalker/ShiftWalkerPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
Fixes all issues in #865 and the issues in the 2 other plugins that used the menuopened event by reverting commit d2cd11a7, also fixes possible concurrent modification issues in menumanager
=> menumanager: fix right click/swap issues

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/flexo/FlexoPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/runeliteplus/RuneLitePlusPlugin.java
flexo made an external plugin
runeliteplus made a utility plugin
flexo disabled by default
load external plugins set to false by default.
=> disable flexo by default

runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerMinimapOverlay.java
Removes max draw distance of ground markers
=> Removes max draw distance of ground markers

injector-plugin/src/main/java/net/runelite/injector/raw/HidePlayerAttacks.java, runelite-api/src/main/java/net/runelite/api/Client.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-client/src/main/java/BufferedSource.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/FontName.java, runescape-client/src/main/java/Model.java, runescape-client/src/main/java/ParamKeyDefinition.java, runescape-client/src/main/java/Projectile.java, runescape-client/src/main/java/TilePaint.java, runescape-client/src/main/java/TriBool.java, runescape-client/src/main/java/WorldMapCacheName.java, runescape-client/src/main/java/WorldMapEvent.java, runescape-client/src/main/java/WorldMapRegion.java, runescape-client/src/main/java/class16.java, runescape-client/src/main/java/class227.java, runescape-client/src/main/java/class25.java, runescape-client/src/main/java/class40.java
Tiny bit of refactoring as well
=> Fix hiding player attacks in client, add option to hide cast as well

runelite-client/src/main/java/net/runelite/client/plugins/clanmanmode/ClanManModeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/clanmanmode/ClanManModePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/multiindicators/MultiIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/pvptools/PvpToolsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/pvptools/PvpToolsPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
fixes clan members always showing walkhere, even when hide options is unticked.
removed option from clanmanmode and added to just pvptools.
removed unneccessary stuff from pvptools
amended menuentryswapper to reflect the new mixins.
amended mixin.
fixes 863
=> Fix PvP issues

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
fixes left click pickpocketing
=> menuentryswapper: add attack to list of options to be swapped for pickpocket.

runelite-api/src/main/java/net/runelite/api/ScriptID.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodePlugin.java, runelite-client/src/main/scripts/SendPublicMessage.rs2asm
Adds a script to send a public message
=> motherlode: add "pay-dirt!" to motherlode mine

runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RunepouchOverlay.java
Reverts runelite-extended/runelite#867
=> runepouch: revert fontmanager integration

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsPlugin.java
=> Boosts: buff/debuff timer fix

runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/ItemType.java, runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/SuppliesTrackerPlugin.java
=> supplies tracker: bug fix

runelite-client/src/main/java/net/runelite/client/plugins/fps/FpsPlugin.java
No longer shuts down the executor when plugin is disabled, but instead sets a flag to prevent it from pinging. This allows the executor to continue being used if the plugin is re-enabled.
Fixes #902
=> fps: fix rejectedexecutionexception

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityOverlay.java
added back overlay draw distance
=> agility: added back overlay draw distance

runelite-api/src/main/java/net/runelite/api/ScriptID.java, runelite-client/src/main/java/net/runelite/client/plugins/chattranslation/ChatTranslationPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/runeliteplus/RuneLitePlusPlugin.java
remove duplicate/invalid scriptids
=> runeliteplus: make bank pin keyboard entry work on all pins

runelite-client/src/main/java/net/runelite/client/util/ping/IcmpEchoReply.java
pr #941 breaks ping indicator ingame, thanks to 789 for finding this
=>  fixed ping not working on current build

pom.xml
=> http-service: fix for not deploying

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
Also fixes issue where colors weren't being set because updateList was doing .equals instead of ==.
=> raids: Add getter to class, so it looks nice

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java
Added Show Friends names on Minimap.
Added Show Clan Member names on Minimap.
https://discordapp.com/channels/373382904769675265/568233625712066591/599020180290666506
=> PlayerIndicators: Added extra 'Name on Minimap' options.

runelite-client/src/main/java/net/runelite/client/plugins/lootassist/LootAssistOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/lootassist/LootPile.java
=> lootpile: Add a couple ticks for the death animation and don't show negative numbers

runelite-api/src/main/java/net/runelite/api/ProjectileID.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeProjectileInfo.java
Superior Gargoyle AOE ID was missing, added it to AoE Warnings
=>  Added Superior Gargoyle AOE warning

runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/BombOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/CrystalBomb.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/ProjectileContainer.java
=> aoewarnings:  rework AoE Warnings to use projectile spawned, rather than projectile moved.

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
=> grandexchangeplugin: fixed duplicate price string

live/bootstrap.json, runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/util/Clipboard.java, runelite-client/src/main/java/net/runelite/client/util/LinkBrowser.java, runelite-client/src/main/java/net/runelite/client/util/bootstrap/Bootstrap.java, runelite-client/src/main/java/net/runelite/client/util/bootstrap/Client.java
ChatCommands: Add Clipboard Support
=> ChatCommands: Add Clipboard Support

pom.xml
disabled IncrementalCompilation
might be causing bugs
=> runelite-client: disabled IncrementalCompilation

runelite-client/src/main/java/net/runelite/client/plugins/reportbutton/ReportButtonPlugin.java
Report button: configgroup fix
now looks at its own config group and updates correctly
=> reportbutton: config group fix

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
Grand Exchange: fix item lookup when selecting item.
fixes #1045
=> grandexchange: fix item lookup when selecting item

runelite-client/src/main/java/net/runelite/client/plugins/chattranslation/ChatTranslationConfig.java
Chat Translator: fixes typo.
fixes #1050
=> chattranslation: fixes typo.

runelite-client/src/main/java/net/runelite/client/plugins/playerscouter/Utils.java
Makes it a bit cleaner looking imo, thanks @Rooty for the suggestion.
=> playerscouter: Always display weapon, and use discord emoji for skull.

runelite-client/src/main/java/net/runelite/client/plugins/dailytaskindicators/DailyTasksPlugin.java
=> dailytaskindicator: Fix plugin

runelite-client/src/main/java/net/runelite/client/plugins/equipmentinspector/EquipmentInspectorPlugin.java
=> equipmentinspectorplugin: Remove the navigation button when disabling the plugin

runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
=> banktags: Fix hidding seperator when opening a tag tab

runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningPlugin.java
Re-Added Superior Gargoyle avoidable ranged projectile.
=> aoewarnings: Re-Added Superior Gargoyle avoidable ranged projectile.

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeItemPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeOfferSlot.java
=> grandexchange: Added ge link

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java
=> Handle player indicator overlays not working due to ring/ammunition

runelite-client/src/main/java/net/runelite/client/plugins/prayeralert/PrayerAlertOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ImageComponent.java
https://i.imgur.com/hPGbkza.png
nice high res screenshot there champ
=> prayeralert: Fix overlaying other infoboxes and widgets

http-api/src/main/java/net/runelite/http/api/chat/ChatClient.java
chatCommands: fix !gc
fixes #1080
=> chatCommands: fix !gc

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
=> slayer: dmm multiplier

runelite-client/src/main/java/net/runelite/client/plugins/tmorph/TMorph.java, runelite-client/src/main/java/net/runelite/client/plugins/tmorph/TMorphConfig.java
https://streamable.com/2px7e
also refactored plugin to follow camelCase
Closes: runelite-extended/runelite#1113
=> tmorph: Add graphic swaps

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
=> slayer: Fix weakness

runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java
GameTick event was missing from subscriptions
=> mining: Fix plugin not showing

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
MenuEntrySwapper: Crystal Impling Jar
=> MenuEntrySwapper: Crystal Impling Jar

runelite-api/src/main/java/net/runelite/api/ProjectileID.java, runelite-client/src/main/java/net/runelite/client/plugins/gauntlet/GauntletPlugin.java
=> gauntlet boss helper : add corrupted projectiles

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Added quick swap to sarachnis crypt.
=> menuentryswapperplugin: Added Sarachnis crypt swap

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsConfig.java
=> playerindicators: Fix labels for agility threshold configs

injector-plugin/build.gradle, runelite-script-assembler-plugin/build.gradle
=> gradle: Close URLClassLoader to prevent leaking file locks

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/plugins/runeliteplus/RuneLitePlusPlugin.java
Fixes Discord RPC, logic was removed in RLP plugin, but never re-implemented.
=> discord: fix init

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/util/bootstrap/Bootstrap.java, runelite-client/src/main/java/net/runelite/client/util/bootstrap/Bootstrapper.java
Bumps version for live update.
also small fix to bootstrap
=> runeliteplus: update / bootstrap

runelite-client/src/main/java/net/runelite/client/plugins/ticktimers/NPCContainer.java
Updated arma mage/range minions aswell as rex.
=> Simple edits to tick timer

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/plugins/privateserver/PrivateServerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/privateserver/PrivateServerPlugin.java, runelite-client/src/main/java/net/runelite/client/rs/ClientLoader.java, runelite-client/src/main/java/net/runelite/client/rs/RSAppletStub.java
runelite-client: restore private server support, remove deprecated arguments
=> runelite-client: restore private server support

build.gradle
=> Gradle: Remove --local-injected

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
next update see's the smithing interface rework - this option is no longer needed
=> Menu Entry Swapper: remove smithing options

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderBridgeMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderMixin.java
=> EntityHider: hide dead NPCs

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderBridgeMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderMixin.java
Closes: https://github.com/runelite-extended/runelite/issues/1173
=> entityhider: Hide selected npcs on death.

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
change widget ID to make the widget moveable.
=> WidgetID: BH Widget Id

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderBridgeMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderMixin.java
i have no idea if this is the correct way to do this but i tested it and it works
=> entityhider: add wildcard support

runelite-client/src/main/java/net/runelite/client/plugins/zulrah/ZulrahInstance.java, runelite-client/src/main/java/net/runelite/client/plugins/zulrah/ZulrahPlugin.java
Thanks, maxed sensei for finding this rare npe.
=> zulrah: Fix NPE

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/util/ConstructionCapeMode.java
=> menuentryswapper: Removed useless telecape, added constructioncape

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-api/src/main/java/net/runelite/api/ProjectileID.java, runelite-client/src/main/java/net/runelite/client/plugins/zalcano/Step.java, runelite-client/src/main/java/net/runelite/client/plugins/zalcano/ZalcanoConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/zalcano/ZalcanoOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/zalcano/ZalcanoPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/zalcano/ZalcanoStepsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/zalcano/ZalcanoUtil.java
Shows AOE for bosses and when to run from the glowing rocks and more.
Still have to improve the step system telling users to mine/smelt so it's a hidden option for now.
=> zalcano: add plugin

runelite-client/src/main/resources/item_variations.json
Added sote items from runelite
=> item_variations: added sote items

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-api/src/main/java/net/runelite/api/MainBufferProvider.java, runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
Skips the config caching changes as we already do it.
=> project: Upstream merge

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/banked/beans/Activity.java
=> Banked XP: Fix Wyrm bones

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/CoxInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/CoxOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/CoxPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/NPCContainer.java, runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/Victim.java, runelite-client/src/main/java/net/runelite/client/plugins/demonicgorilla/DemonicGorillaPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/TheatrePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/SotetsegHandler.java
=> events: reduce projectilemoved usage as much as possible

runelite-client/src/main/java/net/runelite/client/flexo/Flexo.java, runelite-client/src/main/java/net/runelite/client/plugins/flexo/FlexoPlugin.java
Shouldn't effect usage at all, fixes a handful of compile warnings.
=> flexo: remove peer references

runelite-client/src/main/java/net/runelite/client/plugins/gauntlet/GauntletConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/gauntlet/GauntletCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/gauntlet/GauntletInfoBoxOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/gauntlet/GauntletOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/gauntlet/GauntletPlugin.java
* Renamed config options.
* Added config option to turn off projectile overlay.
* added back the prayer infobox.
* added back counter display.
* added back the option to display counters over the boss, in the info box, on both or never.
=> Gauntlet: various updates

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Just pring something Ganom helped me with.
=> menuentryswapperplugin: fixed max cape

deobfuscator/src/test/java/net/runelite/deob/updater/AnnotationCleaner.java, runelite-mixins/src/main/java/net/runelite/mixins/RSRasterizer2DMixin.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/Decimator.java, runescape-client/src/main/java/DynamicObject.java, runescape-client/src/main/java/GameShell.java, runescape-client/src/main/java/GrandExchangeOfferOwnWorldComparator.java, runescape-client/src/main/java/HitSplatDefinition.java, runescape-client/src/main/java/Model.java, runescape-client/src/main/java/ModelData.java, runescape-client/src/main/java/ObjectDefinition.java, runescape-client/src/main/java/Rasterizer2D.java, runescape-client/src/main/java/Scene.java, runescape-client/src/main/java/ScriptFrame.java, runescape-client/src/main/java/ServerBuild.java, runescape-client/src/main/java/Tiles.java, runescape-client/src/main/java/WorldMapRegion.java, runescape-client/src/main/java/class192.java, runescape-client/src/main/java/class40.java
whoops thought that first commit
=> rs-client: Fix project for deob test

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerOverlay.java
The font in the slayer plugin gets set to bold by default for some reason, deleted it.
=> slayer: Font Fix

.travis.yml, injector-plugin/build.gradle, runelite-client/src/test/java/net/runelite/client/plugins/PluginManagerTest.java, runelite-client/src/test/java/net/runelite/client/plugins/chatfilter/ChatFilterPluginTest.java, runelite-client/src/test/java/net/runelite/client/plugins/itemskeptondeath/ItemsKeptOnDeathPluginTest.java, runelite-client/src/test/java/net/runelite/client/plugins/maxhit/calculators/MaxHitCalculatorTest.java, runelite-client/src/test/java/net/runelite/client/plugins/motherlode/MotherlodePluginTest.java, runelite-client/src/test/java/net/runelite/client/util/ItemUtilTest.java
=> client: fix and enable tests

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
=> config: Change slider to white, so its easier to see.

runelite-client/src/main/java/net/runelite/client/plugins/tobdamagecount/DamageCounterPlugin.java
updated spacing and grammar for now may look into more later.
=> damagecounterplugin: updated grammar

build.gradle
Fixes: "repository not found: C:\Users\name\.gradle\daemon\5.5.1.git"
=> gradle: fix "repository not found"

runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/SotetsegHandler.java
Big ball does not always interact with you but you need to know about it
=> Fix Sotes Big balls o.O

runelite-client/src/main/java/net/runelite/client/plugins/raids/shortcuts/ShortcutPlugin.java
otherwise its way down the list
also `raid` > `raids` to match bat finder plugin
=> raids shortcuts: Add PVM plugintype to plugin

build.gradle, cache-client/build.gradle, cache-updater/build.gradle, cache-updater/src/main/java/net/runelite/cache/updater/CacheUploader.java, cache/build.gradle, cache/src/test/java/net/runelite/cache/TitleDumper.java, deobfuscator/build.gradle, http-api/build.gradle, http-service-plus/build.gradle, http-service/build.gradle, http-service/src/main/java/net/runelite/http/service/cache/CacheService.java, injected-client/build.gradle, injector-plugin/build.gradle, protocol-api/build.gradle, protocol/build.gradle, runelite-api/build.gradle, runelite-client/build.gradle, runelite-mixins/build.gradle, runelite-script-assembler-plugin/build.gradle, runescape-api/build.gradle, runescape-client/build.gradle
- Also fixed the TitleDumper test in the cache project
=> gradle: Update deps, format files

runelite-client/src/main/java/net/runelite/client/plugins/kingdomofmiscellania/KingdomConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/kingdomofmiscellania/KingdomPlugin.java
ok I'm stupid and messed up my last PR. sorry about that
here are the changes requested on the last one
=> kingdomofmiscellania: add login chat notification for favor and coffer amount

runelite-client/src/main/java/net/runelite/client/ui/components/InfoPanel.java
=> launcher: make it a lil bit prettier.

runelite-client/src/main/java/net/runelite/client/plugins/playerscouter/PlayerContainer.java, runelite-client/src/main/java/net/runelite/client/plugins/playerscouter/PlayerScouter.java, runelite-client/src/main/java/net/runelite/client/plugins/playerscouter/PlayerScouterConfig.java
Since config caching is now handled by config manager, I'm reverting the local caching being done as well. The performance difference is negligible, but looks much better.
=> playerscouter: fix conmod exception, and various other updates.

runelite-client/src/main/java/net/runelite/client/plugins/tearsofguthix/TearsOfGuthixPlugin.java
=> tearsofguthix: fix npe

runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsPlugin.java
=> barrows: Remove chest value option

runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/banktags/ItemValueSearchTest.java
https://user-images.githubusercontent.com/22979513/62487848-7c476600-b788-11e9-9330-c423f6b906e2.gif
FULL credit to @raiyni, great work!
no horrible overlays.
easy to use
awesome plugin, lets hope upstream bring it in also!
=> banktags: search for valued items

runelite-client/src/main/java/net/runelite/client/plugins/account/AccountPlugin.java
removes login button.
removed all unequipped and underutilised stuff seeing as we dont allow this functionality.
=> account plugin: remove login button

runelite-client/build.gradle, runelite-client/src/main/java/net/runelite/client/flexo/Flexo.java, runelite-client/src/main/java/net/runelite/client/flexo/FlexoMouse.java
Once https://github.com/runelite-extended/runelite/issues/1315 is resolved, we can fully remove flexo.
=> flexo: add back in core class, until (#1315) is resolved.

runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/FreezeTimersPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/Timers.java
=> freezetimers: fix concurrent modification exception

runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java
Added null check for local player and guard case #1338 
closes #1338
=> npcunaggroarea: Local Player NPE Fix

runelite-client/src/main/java/net/runelite/client/plugins/pluginsorter/PluginSorterPlugin.java
=> pluginsorter: fix top entries

runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java
add length check, closes #1313
=> runecraftplugin: add length check

runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/util/ConstructionMode.java
closes #1357
closes #1355
closes #1358
=>  menuentryswapper: various menu fixes and changes

runelite-api/src/main/java/net/runelite/api/events/MenuOptionClicked.java, runelite-client/src/main/java/net/runelite/client/menus/ComparableEntries.java, runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/BankComparableEntry.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/InventoryComparableEntry.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
closes #1234
closes #1367
closes #1362
With this, most menu swaps should be back to 100% functionality.
=> menuentryswapper: various changes and fixes.

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/Parse.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/ShiftClickInputListener.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java
=>  menuentryswapper: remove shift click customisation for a better alternative.

runelite-client/src/main/java/net/runelite/client/plugins/chatboxperformance/ChatboxPerformanceConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/chatboxperformance/ChatboxPerformancePlugin.java
=> chatboxperformance: Toggle chatbox gradient

runelite-client/src/main/java/net/runelite/client/plugins/inferno/InfernoPrayerOverlayMode.java
Inferno: fix plugin start-up error.
=> Inferno: fix plugin start-up error.

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
=> mixins: Add setGameState(Gamestate)

runelite-client/src/main/java/net/runelite/client/plugins/reminders/RemindersConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/reminders/RemindersPlugin.java
Reminders plugin creation.
break reminder:
every hour, you will be reminded to take a 5-10 minute break.
hydration reminder:
every hour, you will be reminded to drink 4oz/120ml of water.
personal reminder:
set your own personal reminder with custom text and time duration.
thanks to jkybtw for the logic, credited in licence info
=> Reminders: added plugin

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java
resolved #1407 by implementing the recommended fix.
=> clanchatplugin: fix issue 1407, UnsupportedOperationException

runelite-client/src/main/java/net/runelite/client/plugins/stonedtracker/ui/LootPanel.java
stonedtracker: changed info to debug
=> stonedtracker: changed info to debug

runelite-api/build.gradle, runelite-api/src/main/java/net/runelite/api/MenuEntry.java, runelite-api/src/main/java/net/runelite/api/util/Text.java, runelite-client/src/main/java/net/runelite/client/menus/BaseComparableEntry.java, runelite-client/src/main/java/net/runelite/client/menus/ItemComparableEntry.java, runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/BankComparableEntry.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/EquipmentComparableEntry.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/InventoryComparableEntry.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/shiftwalker/ShiftWalkerPlugin.java
=> plugins: Fix menu concurrency issues

runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/CoxInfoBox.java
Proper check for olm prayer config, expand guard case closes #1421
=> coxhelper: add proper config check, expand guard case

runelite-client/src/main/java/net/runelite/client/plugins/slayer/TargetClickboxOverlay.java
add guard case to prevent NPE closes #1445
=> slayer: add clickbox guard case

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsPlugin.java
inventory tags: add 4 additional tags
=> inventory tags: add 4 additional tags

runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java
GroundMarkers: add 4 additional markers
=> GroundMarkers: add 4 additional markers

runelite-client/src/main/java/net/runelite/client/RuneLite.java
Sometimes the GPU plugin tried to start when the UI wasn't ready
=> client: Initialize the UI sooner

runelite-client/src/main/java/net/runelite/client/plugins/tmorph/Parse.java, runelite-client/src/main/java/net/runelite/client/plugins/tmorph/TMorph.java
=> tmorph: anim bug fix and move maps to global vars.

runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
=> menumanager: remove click check on menumanager, it's causing more issues than fixing.

runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
=> Revert "menumanager: remove click check on menumanager, it's causing more issues than fixing."

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityPlugin.java, runelite-client/src/main/java/net/runelite/client/util/ColorUtil.java, runescape-client/src/main/java/class225.java, runescape-client/src/main/java/class51.java, runescape-client/src/main/java/class65.java
Adds the color range dependent on how big the difference is between your level and the shortcut like there is for players and npcs
=> Agility plugin: generate less garbage objects + color range

runelite-client/src/main/java/net/runelite/client/plugins/profiles/ProfilesPanel.java
=> profiles: Ui fixes and improvements

runelite-client/src/main/java/net/runelite/client/plugins/safespot/SafeSpotConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/safespot/SafeSpotPlugin.java
=> safespots: remove PVP function

runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/WintertodtPlugin.java
Closes #1470
This reverts commit 297cf7614a8e7277744bdb565ec3a1c4da65be6e.
Will revisit and fix properly later, For now revert the commit and fix the wt overlays.
=> wintertodt: Revert selective eventbus listening

runelite-client/src/main/java/net/runelite/client/plugins/equipmentinspector/EquipmentInspectorPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/gauntlet/GauntletTimer.java
fix chatmessagetypes to use CONSOLE instead of FRIENDSCHATNOTIFICATION
=> global: fix chatmessagetypes

runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java
GroundMarkers: increase number of markers
was requested due to some external functionality requiring more
=> GroundMarkers: increase number of markers

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
=> grounditems: fixes hidden values

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/events/MenuOpened.java, runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/main/java/net/runelite/client/plugins/corp/CorpPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/friendnotes/FriendNotesPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/friendtagging/FriendTaggingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/MenuMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/WorldMapID.java
=> Client: menu changes

runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningConfig.java
pls dont break it this time misto
=> mining: change default pie diameter

runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneConfig.java
=> nightmarezone: fixed typo in config

runelite-client/src/main/java/net/runelite/client/plugins/dropparty/DropPartyPlugin.java
=> dropparty: text standardize

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
=> screenshotplugin: fixed filename/typo

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperConfig.java
=> worldhopper: fixed minor text typos

runelite-client/src/main/java/net/runelite/client/plugins/prayagainstplayer/PrayAgainstPlayerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayagainstplayer/PrayAgainstPlayerOverlayPrayerTab.java, runelite-client/src/main/java/net/runelite/client/plugins/prayagainstplayer/PrayAgainstPlayerPlugin.java, runelite-client/src/main/java/net/runelite/client/util/WeaponType.java
util: move weaponType
WeaponType has been moved so it can be utilised by other plugins too. it has also been updated to reflect newer and missing weapons
=> util: move weaponType

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscoreConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/hiscore/HiscorePanelTest.java
=> hiscore plugin: add config caching

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
* move can afford to the quantity heading to stop text overflow (#1061)
* fix value not updating when changing price (#1061)
* fix NPE when inventory container is null (#1161)
=> grandexchange: fix can afford not updating

build.gradle
Fixes project version to make it consistent with github
=> project: correct version

runelite-client/src/main/java/net/runelite/client/plugins/shiftwalker/ShiftWalkerPlugin.java
=> shiftwalkplugin: only activate if logged in

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsService.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java
re-adds clan member ranks to indicators, fixes misc player indicator bugs
=> Player Indicators: fixes

runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderMixin.java
Unnecessary usage of text.standardize
=> entityhider: fix specific player hiding.

runelite-client/src/main/java/net/runelite/client/plugins/mesenhanced/MesEnhanced.java, runelite-client/src/main/java/net/runelite/client/plugins/mesenhanced/MesEnhancedConfig.java
=> mesenhanced: add "enhanced" features similar to OSB.

runelite-client/src/main/java/net/runelite/client/plugins/dropparty/DropPartyConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/dropparty/DropPartyOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/dropparty/DropPartyPlugin.java
=> dropparty:fix

runelite-client/src/main/java/net/runelite/client/plugins/wildernesslocations/WildernessLocationsConfig.java
PRed again because I fked up original.
=> wildernesslocationsconfig: grammar

runescape-client/src/main/java/ScriptFrame.java
fix issues - RSB_FOX IS THE BOY
thanks fox
=> fix issues - RSB_FOX IS THE BOY

runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/antidrag/CustomCursor.java
Added an option for key hold.
Fixed cursor not changing to normal and using RS3 Gold as default when toggling off.
=> Anti Drag: Hold on Key

runelite-client/build.gradle
Adds a gradle task to copy dependencies to be easily found by bootstrapper
=> Update gradle task for bootstrapper

runelite-client/src/main/java/net/runelite/client/plugins/dynamicmaxhit/DynamicMaxHit.java
DynamicMaxHit: change from external to PVP
=> DynamicMaxHit: change from external to PVP

runelite-client/src/main/java/net/runelite/client/plugins/bronzeman/BronzeManOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/bronzeman/BronzemanPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/bronzeman/ItemUnlock.java
essentially restricts you to be an IronMan, but you can use the GE for items you have already obtained via questing/PVM/PVP.
been highly requested.
=> bronzemanmode

runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/nylocas/Weapons.java
=> tob: fix nullable

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/shiftwalker/ShiftWalkerPlugin.java
=> hotkeylistener: only initialize on valid game state.

runelite-client/src/main/resources/npc_stats.json
This is an auto-generated PR with changes from the OSRS wiki
=> Client: Update item stats

runelite-client/src/main/resources/npc_stats.json
This is an auto-generated PR with changes from the OSRS wiki
=> Client: Update NPC stats

build.gradle
This is an auto-generated PR with an updated gradle dependencies versions
=> project: Update gradle dependencies

build.gradle, checkstyle/checkstyle.xml, runelite-client/src/main/java/net/runelite/client/plugins/gauntlet/GauntletPlugin.java, runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
Fixes the annoying stackoverflowerror
=> project: Update checkstyle

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> menuentryswapper: Fixed bones option being to generic when matching

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/Sprite.java, runelite-api/src/main/java/net/runelite/api/SpriteID.java, runelite-api/src/main/java/net/runelite/api/VarPlayer.java, runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraSceneOverlay.java, runelite-client/src/main/java/net/runelite/client/util/ImageUtil.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-api/src/main/java/net/runelite/rs/api/RSSprite.java
https://cdn.discordapp.com/attachments/596832278504538122/630496934825820180/j1WqWUgSCS.mp4
=> hydra: config options and useless stun timer

runelite-client/src/main/java/net/runelite/client/plugins/tmorph/TMorphConfig.java
closes Suggestion 265 (discord)
=> tmorph: fixed typo

README.md
I could not find what the link for the Build Status is. If anyone could give me pointers, I'd be happy to update.
=> readme: Update Github links to open-osrs

runelite-client/src/main/java/net/runelite/client/plugins/chattranslation/ChatTranslationPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/chattranslation/Languages.java
also easier language selection in config.
=> chat-translator: add additional languages.

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
=> overlayrenderer: Fix font styles not applying

runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/SuppliesTrackerPlugin.java
=> supplytracker: Fix eating and drinking menu actions

runelite-client/src/main/java/net/runelite/client/RuneLite.java
This is causing extra load time now, revert this commit when the bot is back up
=> sessionmanager: Disable until the bot is up and running

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Added Young Implings to mes, checks for beginner OR easy clue in inventory then swaps Loot->Use.
=> mes: beginner/easy clues for Young Implings

runelite-client/src/main/java/net/runelite/client/ClientSessionManager.java, runelite-client/src/main/java/net/runelite/client/SessionClient.java
Currently it's blocking startup, waiting for a response which doesn't really matter anyway (to the client). This is especially noticeable when your connection times out (10 secs of freeze)
=> client: Run SessionClient asynchronously

runelite-api/src/main/java/net/runelite/api/VarPlayer.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/PouchOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java
Thanks to @kecleon for the varPlayer idea/bitmask.
=> runecraft: add pouch degrade overlay.

build.gradle
adds the option to publish artifacts/poms to the github package repo
=> Gradle: add the option to publish maven artifacts/poms to the GH package registry

http-api/src/main/java/net/runelite/http/api/RuneLiteAPI.java
Fixes user count on discord bot.
=> client: update session base URL

runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerConfig.java
=> groundmarkers: Fix typo

.github/workflows/scraper.yml, wiki-scraper/src/main/java/net/runelite/data/App.java
=> scraper: Remove item action and minify json

runelite-client/src/main/java/net/runelite/client/plugins/bank/BankPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/BankSearch.java
=> bankplugin: Faster searching

http-api/src/main/java/net/runelite/http/api/discord/DiscordEmbed.java, http-api/src/main/java/net/runelite/http/api/discord/DiscordMessage.java, runelite-client/src/main/java/net/runelite/client/plugins/playerscouter/PlayerScouter.java
Makes the discord part less generalized, but keep the specific stuff that's needed, and do it in the right way. Removes compilation warnings
=> client: Clean up playerscouter/discord

runelite-api/src/main/java/net/runelite/api/Actor.java, runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoPlugin.java, runescape-api/src/main/java/net/runelite/rs/api/RSActor.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
Also has an option to colour who'm'st've you're attacking. Useful for barraging
=> OpponentInfo: Show hp in menu

.github/CONTRIBUTING.md
confused me for way too long.....when there was loads of old shit appearing
=> contributing: update file.

gradlew, gradlew.bat
This is an auto-generated PR with an updated gradle version
=> project: Update gradle wrapper

runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingPlugin.java
Option to show the amount of gp earned assuming that logs are kept, for the woodcutting plugin.
=> woodcutting: added gp earned for woodcutting

runelite-client/src/main/java/net/runelite/client/eventbus/EventBus.java
not the cleanest solution by any means, but mainly a discussion point.
=> eventbus: crash on runtime error.

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
=> cluescrolls: add tile null check.

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java
=> loottracker: null check

runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
closes https://github.com/open-osrs/runelite/issues/1917
=> menumanager: fix npe on removeswaps

runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerPlugin.java
=> screenmarker: NPE check

runelite-client/src/main/java/net/runelite/client/plugins/raidsthieving/BatSolver/ChestIdentifier.java
Closes https://github.com/open-osrs/runelite/issues/1932
=> batsolver: fix NPE

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
=> cluescroll: NPE check

runelite-client/src/main/java/net/runelite/client/plugins/maxhit/equipment/EquipmentHelper.java
=> maxhit: fix #1941

runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java
=> itemcharge: temp fix for ugly broken recoil code.

runelite-client/src/main/java/net/runelite/client/plugins/raidsthieving/RaidsThievingPlugin.java
=> raidsthieving: NPE check

runelite-client/src/main/java/net/runelite/client/plugins/vorkath/VorkathPlugin.java
=> vorkath: NPE checks

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java, runelite-api/src/main/java/net/runelite/api/widgets/WidgetInfo.java, runelite-client/src/main/java/net/runelite/client/plugins/banlist/BanListPlugin.java
is supposed to close #1370 and #1954 
right?
=> Banlist: various fixes/improvements

runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/SuppliesTrackerPlugin.java
Fully closes #914, which hasn't been resolved for a while. Seeing no one else fix this issue, I thought I'd just do it myself.
=> supplytracker: Fix ammo tracking bug

runelite-client/src/main/java/net/runelite/client/plugins/gauntlet/GauntletPlugin.java
=> gauntlet: Fix npe

injected-client/injected-client.gradle.kts
Fixes injected-client build script so inject doesn't wait until runelite-client:compileJava is done
=> gradle: Make injecting run parallel

runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java
add twisted league support for XP Drops
=> ExperienceDrop: add twisted league support

runelite-client/src/main/java/net/runelite/client/rs/ClientConfigLoader.java, runelite-client/src/main/java/net/runelite/client/rs/ClientLoader.java
DNS: Temp fix for DNS issues
Skitzo wins again
=> DNS: Temp fix for DNS issues

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/NPCDefinition.java, runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderBridgeMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSNPCDefinition.java
- Adds `isFollower()` to NPCDefinition
- Adds hide pets option to entity hider
=> entityhider: Pets entity hider & isFollower

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java
closes suggestion 501 in discord
=> WorldHopper: Remove BH World

runelite-client/src/main/java/net/runelite/client/plugins/whalewatchers/WhaleWatchersPlugin.java
WhaleWatchers: fix phoenix necklace breaking
=> WhaleWatchers: fix phoenix necklace breaking

runelite-client/src/main/java/net/runelite/client/plugins/prayagainstplayer/PrayAgainstPlayerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/prayagainstplayer/PrayAgainstPlayerPlugin.java
PrayAgainstPlayer: Add config option for Highlight
=> PrayAgainstPlayer: Add config option for Highlight

runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingListener.java, runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingPlugin.java
KeyMapping: Add additional key remapping
supports shift, ctrl and alt.
=> KeyMapping: Add additional key remapping

runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/main/java/net/runelite/client/plugins/wiki/WikiPlugin.java
`hashmultimap.get(key)` pretty much acts like `map.get(key, new HashMap())`, resulting in a lot of maps if you don't call contains
=> client: Re-optimize wikiplugin, call contains on hashmultimap in menumanager

runelite-client/src/main/java/net/runelite/client/plugins/bank/BankConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/bank/BankPlugin.java
1) Added right click option for setting placeholders.
2) Added right click option for releasing placeholders.
3) Added right click option for search.
4) Added right click option for fill bank fillers.
5) Tidied up the config section.
6) Changed config.bla to this.bla within the plugin.
=> Bank: additional feautres + tidy up

runelite-client/src/main/java/net/runelite/client/plugins/openosrs/OpenOSRSPlugin.java
=> OpenOSRS: fix hiding plugins

runelite-mixins/src/main/java/net/runelite/mixins/RSAbstractArchiveMixin.java
Profiler was showing multiple for every overlaid script
=> mixins: Make sure cache overlay inputstreams are closed

runelite-client/src/main/java/net/runelite/client/plugins/prayagainstplayer/PrayAgainstPlayerOverlay.java
this was missed from the original PR 2100....
=> prayagainstplayer: highlighting

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
MES: add left click last destination
=> MES: add left click last destination

runelite-client/src/main/java/net/runelite/client/plugins/profiles/ProfilePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/profiles/ProfilesConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/profiles/ProfilesPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/profiles/ProfilesPlugin.java
1) renamed "isStreamerMode" to "streamerMode"
2) changed profiles panel to use updateconfig() rather than config.bla
3) added in auto panel refreshing on config change.
4) added the ability to hide the "email address" field to declutter panel when having multiple accounts.
=> profiles: various

runelite-client/src/main/java/net/runelite/client/util/PvPUtil.java
In Deadman mode, anyone from lvl 3-126 is attackable.
=> IdleNotifier: change isAttackable to support deadman mode

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/ActionType.java, runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/BlowpipeDartType.java, runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/ItemType.java, runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/MenuAction.java, runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/Runes.java, runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/SuppliesTrackerItem.java, runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/SuppliesTrackerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/ui/SuppliesBox.java, runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/ui/SuppliesTrackerPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/ui/UpdatePanel.java, runelite-client/src/main/resources/net/runelite/client/plugins/suppliestracker/ui/Info.html
1. Added rune pouch support
2. Added elf blade tracking
3. Several bug fixes
4. Added standard combat and high high tracking
5. Added fire rune tracking
=> Suppliestracker: Rework a bit, added standard cmb spells, rune pouch

runelite-client/src/main/java/net/runelite/client/plugins/inventorysetups/InventorySetupPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/inventorysetups/ui/InventorySetupPluginPanel.java
Added alphabetical sorting to the InventorySetups combobox because it was tilting me.
[Before](https://i.imgur.com/JI4GYFj.gifv)
[After](https://i.imgur.com/Kdeggfg.gifv)
PS: First ever commit/PR, please be gentle
=> inventorysetups: Add sorting to the JComboBox

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java
=> devtools: add npc index

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
menuentryswapper: unbreak jewellery box
=> menuentryswapper: unbreak jewellery box

runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java
groundmarkers: fix 10, 11 & 12 not displaying
=> groundmarkers: fix 10, 11 & 12 not displaying

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/TileModel.java, runelite-client/src/main/java/net/runelite/client/plugins/minimap/MinimapConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/minimap/MinimapPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSSceneMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSSpriteMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSTileModelMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-api/src/main/java/net/runelite/rs/api/RSScene.java, runescape-api/src/main/java/net/runelite/rs/api/RSTilePaint.java
I would point to the runelite pull req, and @ the original author, but I don't think Adam & co enjoy that, so just search for it yourself :)
=> Client: add hd minimaps

runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java
Show item charges on the Kharedst's Memoirs book.
=> Plugin: Add Kharedst's Memoirs to ItemChargePlugin

buildSrc/src/main/kotlin/BootstrapTask.kt
=> bootstrap: fix nightly

runelite-client/src/main/java/net/runelite/client/plugins/raids/Raid.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ImageComponent.java
Fixed the !layout NPE & updated RaidOverlay (asked & approved by Emil & kyle in discord#support)
[Screenshot of overlay](https://imgur.com/a/Cndl8HX)
=> raids: Fix !layout command & update RaidOverlay

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
menuentryswapper: Left Click Banking
=> menuentryswapper: Left Click options within Bank

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> mes: fix mounted capes

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldSwitcherPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldTableRow.java
=> project: upstream

runelite-api/src/main/java/net/runelite/api/Tile.java, runelite-api/src/main/java/net/runelite/api/TileObject.java, runelite-api/src/main/java/net/runelite/api/queries/TileQuery.java
A new type of query to search for a specific tile.
Example usage:
`			Tile tile = new TileQuery()
.atWorldLocation(OBSTACLE.getWorldPoint())
.isWithinDistance(client.getLocalPlayer().getWorldLocation(), MAX_DISTANCE)
.result(client)
.first();`
=> Query: TileQuery

runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeItemPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeSearchPanel.java
@Adam- requested to have these removed since they cause a lot of API calls
=> client: Remove OSB prices from examing and from the GE JPanel

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/comparables/BankComparableEntry.java
priority was being overridden on shiftclick by deposit-xxx
=> mes: fix left click bank options

buildSrc/src/main/kotlin/Dependencies.kt
=> injector: Dependancies update

runelite-api/src/main/java/net/runelite/api/MenuOpcode.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java, runelite-client/src/main/java/net/runelite/client/plugins/camera/CameraPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItem.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/LootType.java, runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/suppliestracker/SuppliesTrackerPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/WorldHoppingMixin.java
=> upstream: merge

runelite-client/src/main/java/net/runelite/client/plugins/statusorbs/StatusOrbsPlugin.java
statusorbs: remove twisted league stuff
=> statusorbs: remove twisted league stuff

runelite-api/src/main/java/net/runelite/api/Varbits.java
varbits: remove twisted league
=> varbits: remove twisted league

runelite-client/src/main/java/net/runelite/client/plugins/leftclickonly/LeftClickOnlyPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/leftclickonly/RightClickConsumer.java
leftclickonly: add plugin
original plugin:
https://github.com/dekvall/left-click-only
=> leftclickonly: add plugin

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
mes: add npc contact & hotkey description cleanup
=> mes: add npc contact & hotkey description cleanup

http-api/src/main/java/net/runelite/http/api/RuneLiteAPI.java, http-api/src/main/java/net/runelite/http/api/sounds/SoundsClient.java, runelite-client/src/main/java/net/runelite/client/plugins/sounds/SoundsPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/SoundEffectMixin.java
Captures all NPC sounds and uploads them to our service at sounds.openosrs.dev if they don't yet exist.
=> plugins: add sounds service plugin

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPluginConfig.java, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/frag.glsl
Lighting is based on current area's fog color.
This is a very basic example of working with the gpu plugin / OpenGL shaders,
=> gpu: add ambient lighting

.github/workflows/scraper.yml, runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/annotations/VisibleForExternalPlugins.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/VarbitMixin.java
=> runelite-client: add methods for externals (plugin-hub)

runelite-client/src/main/java/net/runelite/client/util/MiscUtils.java, runelite-client/src/main/java/net/runelite/client/util/PvPUtil.java
pvpupdate: attackable pvp world levels from 15 to 10
=> pvpupdate: attackable pvp world levels from 15 to 10

runelite-client/src/main/java/net/runelite/client/util/MiscUtils.java, runelite-client/src/main/java/net/runelite/client/util/PvPUtil.java
Reverts open-osrs/runelite#2293
=> pvpupdate: attackable pvp world levels from 10 to 15

runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/hideunder/HideUnder.java
we don't limit other regions/minigames, so i dont see why we need to limit castle wars.
also cleaned up entityhider a little.
=> entityhiding: remove cwars limitation

build.gradle.kts, jitpack.yml
This got broken in commit 1117eba, fixed now though HYPERS
https://jitpack.io/com/github/open-osrs/runelite/jitpack-f2478b86da-1/build.log
=> gradle: fix jitpack publishing

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
=> clientui: client focus

runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPanel.java
info: update plugins directory
=> info: update plugins directory

runelite-client/src/main/java/net/runelite/client/plugins/PluginDescriptor.java, runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java
=> plugins: re-add enabledByDefault

buildSrc/src/main/kotlin/Dependencies.kt
=> version: bump

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-mixins/src/main/java/net/runelite/mixins/ClickboxMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/ComplianceMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSSceneMixin.java
To be merged at the same time as open-osrs/plugins#72
=> detachedcamera: interaction

http-api/src/main/java/net/runelite/http/api/RuneLiteAPI.java, http-api/src/main/java/net/runelite/http/api/chat/ChatClient.java
api: who even thought this was a good idea????
=> api: who even thought this was a good idea????

.github/workflows/stale.yml
This is just kinda useless tbh
=> actions: don't autoclose stale issues/prs

runelite-api/src/main/java/net/runelite/api/util/Text.java, runelite-client/src/main/java/net/runelite/client/plugins/openosrs/externals/PluginsPanel.java
pluginpanel: update to use text utils
=> pluginpanel: update to use text utils

runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginManager.java, runelite-client/src/main/java/net/runelite/client/plugins/openosrs/externals/ExternalPluginManagerPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/openosrs/externals/PluginsPanel.java, runelite-client/src/main/java/net/runelite/client/ui/ClientPanel.java, runelite-client/src/main/java/net/runelite/client/util/LinkBrowser.java
=> alwaysontop: Always set a parent component to prevent components from rendering behind the main panel

runelite-client/src/main/java/net/runelite/client/RuneLite.java
sometimes, counting can be a bit hard
=> splashscreen: fix percentage

runelite-client/src/main/java/net/runelite/client/ws/WSClient.java
Closes #2443
https://i.imgur.com/vJJordO.png
=> party: fix websocket events not being posted

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/input/MouseManager.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/Overlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
Reverts open-osrs/runelite#2451
=> Revert "upstream: merge"

runelite-client/src/main/java/net/runelite/client/input/MouseManager.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/Overlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
upstream: i actually hate git desktop
=> upstream: i actually hate git desktop

.github/release-drafter.yml, .github/workflows/push.yml
squash merge this otherwise ill shoot a bullet train at your house and toss your salad
=> actions: fix release drafter

README.md
Added binaries link to README.md
=> project: Added binaries link to README.md

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
=> boosts: fix statchanged event

runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginManager.java
externals: catch invalid plugintype exceptions
=> externals: catch invalid plugintype exceptions

runelite-client/src/main/java/net/runelite/client/RuneLite.java
This is definitely not the best solution, for instance if something happens asynchronously(how?) and the config manager somehow reaches it during a file lock, it could possibly be overwritten, thus  deleting users configs.
Tested and working currently.
=> client: parse launcher config before client init.

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
=> overlayRenderer: add check before rendering

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
java.lang.NumberFormatException: null
at java.lang.Integer.parseInt(Integer.java:620)
at java.lang.Integer.parseInt(Integer.java:776)
at net.runelite.client.plugins.config.ConfigPanel.rebuild(ConfigPanel.java:587)
at net.runelite.client.plugins.config.ConfigPanel.init(ConfigPanel.java:238)
at net.runelite.client.plugins.config.PluginListPanel.openConfigurationPanel(PluginListPanel.java:429)
at net.runelite.client.plugins.config.PluginListItem.openGroupConfigPanel(PluginListItem.java:264)
at net.runelite.client.plugins.config.PluginListItem.lambda$new$2(PluginListItem.java:194)
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
at …
=> configpanel: Catch NumberFormatException

runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginManager.java, runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java
project: splash screen change and more logging
=> project: splash screen change and more logging

runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java
project: splashscreen fix capitalisation
=> project: splashscreen fix capitalisation

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/PanelComponent.java
This fixes an issue where panels did not want to be dynamically resized.
=> panelcomponent: add override for panel resizing.

runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginManager.java
externalpluginmanager: add verbose debug logging.
=> externalpluginmanager: ensure no duplicates are saved to config.

runelite-client/runelite-client.gradle.kts, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
I will add this thing to the dev tools plugin if this gets accepted https://i.imgur.com/L0atLKQ.gifv
=> project: add groovy dependency

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
To create a button, use the following:
```java
@ConfigItem(
name = "Button Text",
keyName = "uniqueString",
description = "This button does stuff :)"
)
default Consumer<YourPluginClass> keyNameHere()
{
return (plugin) -> {
// code here gets run when button is clicked
};
}
=> config: add buttons

runelite-client/src/main/java/net/runelite/client/callback/Hooks.java
=> hooks: expose overlay renderer

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
Adds support to selectively send mirror draw events. should save some resources if you aren't actually using the plugin.
=> api: add mirror api

runelite-client/src/main/java/net/runelite/client/callback/Hooks.java
=> project: checkstyle fix

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
=> project: widget Index OOB fix

runelite-client/src/main/java/net/runelite/client/plugins/Plugin.java
Event handlers shouldn't throw checked exceptions (preferably no exceptions at all, but you know..). This logs what plugin is doing it wrong, and sends it to owain's personal email address (also known as sent-ree). This should probably be replaced with an assertion (after a few weeks?), so people don't accidentally do this when writing their own plugins.
=> client: Nag user (and sentry) if event handlers declare to throw an exception

runelite-api/src/main/java/net/runelite/api/VarClientInt.java
project: add dmm safezone varclientint
=> project: add dmm safezone varclientint

runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginManager.java
Also name threads for easy identification
The diff looks big, but I just wrapped the code block with a try-finally and applied the formatting from https://discordapp.com/channels/373382904769675265/573915896309874698/621451864470192159
=> Client: Shutdown ExecutorService in ExternalPluginManager

runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginManager.java, runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java
Same as https://github.com/open-osrs/runelite/pull/2610
=> client: Also shutdown executor in PluginManager

runelite-client/src/main/java/net/runelite/client/config/OpenOSRSConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginManager.java, runelite-client/src/main/java/net/runelite/client/plugins/openosrs/externals/RepositoryBox.java
project: add pluginhub as a default repository
=> project: add pluginhub as a default repository

runelite-client/runelite-client.gradle.kts
Reverts open-osrs/runelite#2616
=> Revert "rxrelay: Pull artifact from mvn"

runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginManager.java, runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java
TODO: Rewrite so that plugin manager and external plugin manager use the same function instead of duplicating code
=> externalpluginmanager: Mimic PluginManager.scanAndInstantiate closer

runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBox.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxManager.java, runelite-client/src/test/java/net/runelite/client/ui/overlay/infobox/InfoBoxManagerTest.java
revert, of the revert of the initial commit
=> infobox: make threadsafe

runelite-client/runelite-client.gradle.kts, runelite-client/src/main/java/net/runelite/client/ui/skin/ObsidianSkin.java
This reverts commit 6d7046af4d249bd67af120a12a7f9aa18e2637fc.
=> radiance: Revert update

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
=> lowmemory: refresh scene when toggling plugin

runelite-api/src/main/java/net/runelite/api/Actor.java, runelite-api/src/main/java/net/runelite/api/Point.java, runescape-api/src/main/java/net/runelite/rs/api/RSActor.java, runescape-client/src/main/java/Actor.java, runescape-client/src/main/java/ClientPacket.java, runescape-client/src/main/java/GrandExchangeOffer.java, runescape-client/src/main/java/NPC.java, runescape-client/src/main/java/NPCDefinition.java, runescape-client/src/main/java/Player.java, runescape-client/src/main/java/WorldMapSection0.java, runescape-client/src/main/java/class22.java, runescape-client/src/main/java/class41.java
Adds an offset method to point for utility.
Renames `readySequence` to `idleSequence` in `Actor` and `NPCDefinition`
Adds getter methods for movement-based animations for `Actor`s
=> api: add methods for extended player dev tools

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
configmanager: log null defaults without crashing
=> configmanager: log null defaults without crashing

runelite-client/src/main/java/net/runelite/client/util/WeaponMap.java
=> weaponmap: add missing items

runelite-client/src/main/java/net/runelite/client/config/OpenOSRSConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginManager.java, runelite-client/src/main/java/net/runelite/client/plugins/openosrs/externals/ExternalPluginManagerPanel.java
=> aaaaa: dammit op

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/ui/components/SliderUI.java, runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
Not a radiance substance slider, but it fits a lot better with the GUI than our current weird white one.
=> client: Custom slider

runelite-client/src/main/java/net/runelite/client/RuneLite.java
=> client: Respect symlinks for the config file

runelite-api/src/main/java/net/runelite/api/AnimationID.java
=> animationid: change private vars to public

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TextComponent.java
This was causing insane garbage generation in overlays (fixes #2279)
=> client: Make TextComponent not blend text color with color below by default

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
https://gfycat.com/VillainousAdolescentFantail
easily tested with open-osrs/plugins#337
=> mixins: Bring player targeted by hint arrow to front (while not in combat)

runelite-mixins/src/main/java/net/runelite/mixins/RSActorMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSTileMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSNodeDeque.java
=> grounditems: fix items not disappearing

build.gradle.kts, injected-client/injected-client.gradle.kts
=> gradle: update injector version

build.gradle.kts, runelite-api/src/main/java/net/runelite/api/events/ScriptPreFired.java, runelite-mixins/src/main/java/net/runelite/mixins/ScriptVMMixin.java
Depends on https://github.com/open-osrs/openosrs-injector/commit/dbaa4d993c80b4337a69e9516242287ebe326ff3 being put back and then injector to be updated in hosting repository.
=> mixins: make scriptvm more reliable

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/IndexDataBase.java, runelite-api/src/main/java/net/runelite/api/VarbitComposition.java, runelite-api/src/main/java/net/runelite/api/VarbitDefinition.java, runelite-mixins/src/main/java/net/runelite/mixins/VarbitMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSAbstractArchive.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-api/src/main/java/net/runelite/rs/api/RSVarbitDefinition.java
also merges upstream var inspector changes - do not merge without merging the plugins pr
=> api: var stuff

runelite-mixins/src/main/java/net/runelite/mixins/ScriptVMMixin.java
This fixes the script vm mixin consuming all script events that aren't `JavaScriptCallback`s crafted by plugins or raw script ids, meaning `WorldMapEvent`s would be consumed silently, breaking the world map click-to-go-to-dungeon scripts.
=> scriptvmmixin: fix consuming WorldMapEvents and potentially others

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
These widgets were shifted by 1
=> rl-api: fix stat bonus widgets

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
to be acknowledged rather than wait for input
=> rl-config: adjust warning dialogs 

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/game/LootManager.java
Fixes loot tracking for The Nightmare
=> LootManager: Nightmare Fix

build.gradle.kts, injected-client/injected-client.gradle.kts, runelite-client/src/main/java/net/runelite/client/plugins/ExternalPf4jPluginManager.java
Also removes publishing sources jars as it was wrong lol
=> pluginmanager: only load jar plugins from the folder

runelite-client/src/main/java/net/runelite/client/plugins/PluginType.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListPanel.java
Its been bugging me for a while, not gonna lie.
=> plugintype: Rename important to system.

runelite-api/src/main/java/net/runelite/api/Varbits.java
=> varbit: add prayer unlocks

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-mixins/src/main/java/net/runelite/mixins/VerboseInventoryMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/VerboseInventoryQuantitiesMixin.java, runescape-client/src/main/java/ChatChannel.java, runescape-client/src/main/java/class194.java
A toggle which makes it possible to show full lenght inventory quantities.
=> api: Add support for verbose inventory quantities

runelite-client/src/main/java/net/runelite/client/util/WeaponMap.java
=> weaponmap: update

runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
Pending review from @Lucwousin 
Tested at 2-50 fps with no hitches.
=> menumanager: restore force left click functionality.

runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
This reverts commit 9400d1a94daf57b0f1a3f79e8ebd99e1434ee201.
That commit causes issues with drag as is.
=> revert: 9400d1a

build.gradle.kts, cache/cache.gradle.kts, deobfuscator/deobfuscator.gradle.kts, http-api/http-api.gradle.kts, runelite-api/runelite-api.gradle.kts, runelite-client/runelite-client.gradle.kts, runelite-client/src/main/java/net/runelite/client/plugins/Plugin.java, runelite-client/src/main/java/net/runelite/client/ui/ClientPanel.java, runelite-mixins/runelite-mixins.gradle.kts, runelite-script-assembler-plugin/runelite-script-assembler-plugin.gradle.kts, runescape-client/runescape-client.gradle.kts, wiki-scraper/wiki-scraper.gradle.kts
This is an auto-generated PR with an updated gradle dependencies
=> gradle: Update gradle dependencies

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSPlayerMixin.java
This partially resolves the issue that generated a lot of junk objects.
=> client: make appearance comparison opt in.

runelite-client/src/main/java/net/runelite/client/util/WeaponMap.java
weaponmap: add missing weapons
=> weaponmap: add missing weapons

runelite-client/src/main/java/net/runelite/client/SessionClient.java
=> session: handle uuid parsing failure

runelite-client/src/main/java/net/runelite/client/util/WeaponMap.java
=> project: update weaponmap

runelite-api/src/main/java/net/runelite/api/AnimationID.java
=> project: add animationids

runelite-client/src/main/java/net/runelite/client/game/LootManager.java
Update lootManager with upstream to fix Nightmare in loottracker.
=> project: upstream lootManager to fix Nightmare in loottracker.

build.gradle.kts, config/checkstyle/checkstyle.xml, deobfuscator/src/main/java/net/runelite/asm/Interfaces.java, openosrs-injector/openosrs-injector.gradle.kts, openosrs-injector/src/main/java/com/openosrs/injector/Injection.java, openosrs-injector/src/main/java/com/openosrs/injector/injectors/MixinInjector.java, runelite-api/src/main/java/net/runelite/api/widgets/Widget.java, runelite-client/src/main/java/net/runelite/client/config/FontType.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSWidgetMixin.java
Fixes checkstyle, modernizer and make the injector output a bit better though probably irrelevant and doesn't change anything at all, RL does it so I'm doing it. Probably makes bytecode more valid or something but idc. TMB.
=> rl: fix stuff

runelite-mixins/src/main/java/net/runelite/mixins/RSModelDataMixin.java
"why should we care about you if you dont report bugs to us" - adam 2019
i helped you fix bugs, you help me.
=> mixins: fix texture uv flip

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/SpritePixels.java, runelite-api/src/main/java/net/runelite/api/events/WorldChanged.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSPlayerMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/VarbitMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/Frames.java, runescape-client/src/main/java/GrandExchangeOfferUnitPriceComparator.java, runescape-client/src/main/java/Messages.java, runescape-client/src/main/java/ModeWhere.java, runescape-client/src/main/java/Players.java, runescape-client/src/main/java/ScriptFrame.java, runescape-client/src/main/java/UserComparator9.java, runescape-client/src/main/java/VarcInt.java, runescape-client/src/main/java/WorldMapData_1.java, runescape-client/src/main/java/WorldMapID.java, runescape-client/src/main/java/WorldMapRectangle.java, runescape-client/src/main/java/class200.java, runescape-client/src/main/java/class231.java, runescape-client/src/main/java/class277.java
=> project: bringup api - thank you blue!

runelite-client/src/main/java/net/runelite/client/Notifier.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListItem.java, runelite-client/src/main/java/net/runelite/client/plugins/config/PluginToggleButton.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/ui/SplashScreen.java, runelite-client/src/main/java/net/runelite/client/ui/components/FlatTextField.java, runelite-client/src/main/java/net/runelite/client/ui/components/materialtabs/MaterialTab.java, runelite-client/src/main/java/net/runelite/client/util/ImageUtil.java, runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
change brand colour to blue from orange.
change star colour to blue.
change config on toggle to blue.
change runelite logo to openosrs.
=> various: fixes

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderBridgeMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderMixin.java
adding to runelite branch for use with the new api
=> add ability to hide npc by index value - andrewterra

runelite-api/src/main/java/net/runelite/api/Client.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
The client reads the cache files into these archives, so if you wanted to read the cache, you would read it from these.
=> client: added api to get cache archives

runelite-api/src/main/java/net/runelite/api/Buffer.java, runelite-api/src/main/java/net/runelite/api/Client.java, runescape-api/src/main/java/net/runelite/rs/api/RSBuffer.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
You would use this if you wanted to pack things into cache files, or export cache files.
=> client: Added api to create and write to byte buffers

runelite-client/src/main/java/net/runelite/client/config/ConfigItem.java, runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java, runelite-client/src/main/java/net/runelite/client/config/ConfigTitle.java, runelite-client/src/main/java/net/runelite/client/config/ConfigTitleDescriptor.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
The titles are implemented like sections are (They still allow nesting)
```java
@ConfigTitle(
name = "title 0",
description = "",
position = 4
)
String title0 = "title0";
@ConfigItem(
keyName = "Config3",
name = "Config 3",
description = "3",
position = 5,
title = title0
)
default boolean Config3()
{
return true;
}
```
=> config: Support for titles

http-api/src/main/java/com/openosrs/http/api/discord/DiscordClient.java, http-api/src/main/java/com/openosrs/http/api/discord/DiscordEmbed.java, http-api/src/main/java/com/openosrs/http/api/discord/DiscordMessage.java, http-api/src/main/java/com/openosrs/http/api/discord/embed/AuthorEmbed.java, http-api/src/main/java/com/openosrs/http/api/discord/embed/FieldEmbed.java, http-api/src/main/java/com/openosrs/http/api/discord/embed/FooterEmbed.java, http-api/src/main/java/com/openosrs/http/api/discord/embed/ImageEmbed.java, http-api/src/main/java/com/openosrs/http/api/discord/embed/ProviderEmbed.java, http-api/src/main/java/com/openosrs/http/api/discord/embed/ThumbnailEmbed.java, http-api/src/main/java/com/openosrs/http/api/discord/embed/VideoEmbed.java
=> project: add discord api

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/RuneLiteProperties.java, runelite-client/src/main/java/net/runelite/client/plugins/defaultworld/DefaultWorldPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
project: proxy and world support
--proxy USERNAME:PASSWORD
--proxy IP:PORT:USERNAME:PASSWORD
--world WORLD
=> project: proxy and world support

runelite-api/src/main/java/net/runelite/api/Tile.java, runescape-api/src/main/java/net/runelite/rs/api/RSTile.java
Add setWallObject functionality to the Api.
=> RSTile: setWallObject

runelite-api/src/main/java/net/runelite/api/TileObject.java, runelite-api/src/main/java/net/runelite/api/queries/TileObjectQuery.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSTileObjectMixin.java
mixins/api: fix broken mixin + more
fix broken mixins
add new mixins
add new api support
=> mixins/api: fix broken mixin + more

runelite-client/src/main/java/com/openosrs/client/util/WeaponMap.java
=> WeaponMap: Fix Typo

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/com/openosrs/client/game/XpDropEvent.java, runelite-client/src/main/java/net/runelite/client/plugins/friendschat/FriendsChatPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderBridgeMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderMixin.java
=> project: add missing features

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/game/ItemManager.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/item/MultipleOfItemRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/item/SingleItemRequirement.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
This fixes plugin-hub plugins that rely on the api
such as: Bank Value
=> api: getItemDefinition > getItemComposition

runelite-api/src/main/java/net/runelite/api/Tile.java, runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListPanel.java, runescape-api/src/main/java/net/runelite/rs/api/RSTile.java
Adds a setter for DecorativeObjects like the other objects have.
=> RSTile: setDecorativeObject

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-mixins/src/main/java/net/runelite/mixins/RSGameObjectMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSTileMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSGameObject.java
=> mixins: fix gameobject spawn/despawn being fucked

runescape-client/src/main/java/TextureProvider.java
This fixes low FPS with the GPU plugin enabled
=> rs-client: fixes wrong capacity getter

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
this fixes #2971 and imbued heart not being detected
=> fix boosted skills

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
=> overlayrenderer: add widget name as tooltip on ALT + hover

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityOverlay.java
Fixes issue with the offset of mark of grace highlighter 
**Before: **
https://i.imgur.com/kqHSvMo.png
**After:**
https://i.imgur.com/qqehBYK.png
=> client: fix the mark of grace highlighter to highlight the correct plane

buildSrc/src/main/kotlin/Dependencies.kt
Bump RL Version to get worldservice / ge prices...
also bumped oprs version idk if that mattered..
=> Project: Bump RL Version.

runelite-api/src/main/java/net/runelite/api/ObjectComposition.java, runelite-mixins/src/main/java/net/runelite/mixins/RSObjectCompositionMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSBuffer.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-api/src/main/java/net/runelite/rs/api/RSObjectComposition.java, runescape-client/src/main/java/ObjectComposition.java, runescape-client/src/main/java/ObjectSound.java, runescape-client/src/main/java/class140.java, runescape-client/src/main/java/class18.java, runescape-client/src/main/java/class7.java
GeChallengeM wanted this for pathfinding stuff.
=> client: object composition directional access bitmask

runelite-client/runelite-client.gradle.kts, runelite-client/src/main/java/net/runelite/client/ui/skin/ObsidianSkin.java, runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
fixes weird green tint in plugin list
=> ui: fixed green tint in plugin list

README.md
hitcounter now works, updated discord link to use server vanity URL
=> readme: fixed hitcounter and discord link

README.md
intellij preview was off a bit
=> readme: newline

buildSrc/src/main/kotlin/Dependencies.kt, runescape-api/src/main/java/net/runelite/rs/api/RSObjectSound.java
=> api: fix sound api import

README.md
dwyl keep resetting hitcounters
=> readme: fixed hitcounter

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
not the best but better than nothing
=> ConfigManager: backwards compatible for some plugins

codebase
private servers no longer supported
=> codebase: removed

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
in my defense. it was 3 am when I made the commit
=> client: Fix PR #3097

runescape-api/src/main/java/net/runelite/rs/api/RSWallDecoration.java, runescape-client/src/main/java/Scene.java, runescape-client/src/main/java/WallDecoration.java
somehow forgot this one, thanks emil
=> mixin: getZ for WallDecoration

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java
This reverts commit 8b3f129c1edcaf66354d392a3523edd93720fdd9.
=> devtools: reverts removal of inventory tool

runescape-api/src/main/java/net/runelite/rs/api/RSActor.java
Untested, no clue if these are accurate, haven't added mixins in a while.
=> rs-api: add missing setter mixins.

runelite-mixins/src/main/java/net/runelite/mixins/ScriptVMMixin.java
=> script-vm: add default handler for mes callbacks.

buildSrc/src/main/kotlin/Dependencies.kt, runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/overlay/OverlayIndex.java, runelite-mixins/src/main/java/net/runelite/mixins/RSAbstractArchiveMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
This PR adds the ability to inject custom client scripts into the game and call them from your external plugins.
I've also created a script assembler gradle task at https://github.com/open-osrs/gradle-script-assembler and provided the required build gradle modifications in https://github.com/open-osrs/example-external-plugin/commit/1d2a3452e80dd0873640b684bf04e542ad6afa79
=> client: add ability to inject custom cs2 scripts

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
event.getItemId() is not valid after the next tick, so can't be called in the inv change callback
=> project: Merge upstream

runelite-client/src/main/java/com/openosrs/client/game/WorldLocation.java
WorldLocation - add lumbridge castle bank
=> WorldLocation - add lumbridge castle bank

runescape-client/src/main/java/FriendLoginUpdate.java, runescape-client/src/main/java/MilliClock.java, runescape-client/src/main/java/PlayerComposition.java, runescape-client/src/main/java/Projectile.java, runescape-client/src/main/java/UserComparator6.java, runescape-client/src/main/java/Widget.java, runescape-client/src/main/java/class14.java, runescape-client/src/main/java/class435.java, runescape-client/src/main/java/class437.java, runescape-client/src/main/java/class67.java
thanks polar for DBRow/TableType
=> rsc: fix sprite mapping

build.gradle.kts, buildSrc/src/main/kotlin/BootstrapTask.kt, runelite-client/runelite-client.gradle.kts
=> project(gradle): Oopsie

runelite-client/src/main/java/com/thatgamerblue/snake/Direction.java, runelite-client/src/main/java/com/thatgamerblue/snake/GameHandler.java, runelite-client/src/main/java/com/thatgamerblue/snake/SnakeGame.java, runelite-client/src/main/java/com/thatgamerblue/snake/SnakePart.java, runelite-client/src/main/java/net/runelite/client/RuneLite.java
Reverts open-osrs/runelite#3226
=> client: snake is back on the menu boys
