- runelite-client/src/main/java/net/runelite/client/rs/bytecode/ByteCodePatcher.java
- runelite-client/src/main/java/net/runelite/client/rs/bytecode/transformers/ErrorTransform.java
Adds ErrorTransform
-This prevents the client from sending any stack traces to Jagex. (a huge client detection system they use)
(also classes contained in the runelite package should already be ignored but this is to be sure, and include libraries such as natural mouse motion from sending errors too.)
> ByteCodePatcher

- runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/Hydra.java
- runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraPhase.java
- runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraPoisonOverlay.java
Other than improving recovery from unexpected situations and improving poison overlay add a fountain outline, (shows up red if the hydra is not on it, green if it's on it, and dissappears when the hydra reeee'd)
> Alch hydra: Improve poison overlay, add defence overlay, bugfixes

- runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java
kyleToday at 12:38 PM
> @formatme
> That damage xp drop whilst fishing
> What a ducking nightmare that will be to fix
`Showing 1 changed file with 5 additions and 0 deletions. `
> XPdrop: Don't show damage indicators on fishing spots

- runelite-client/src/main/java/net/runelite/client/plugins/spellbook/SpellbookPlugin.java
- runelite-client/src/main/scripts/MagicSpellBookRedraw.rs2asm
This fixes a npe when loading the plugin with empty config (aka everyone)
you can run maven on only client to make it go by faster, sorry :(
> load spells only once per rebuild instead of before adding a new spell

- runelite-api/src/main/java/net/runelite/api/Projectile.java
- runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java
- runelite-client/src/main/java/net/runelite/client/rs/bytecode/transformers/ActorTransform.java
- runelite-client/src/main/java/net/runelite/client/rs/bytecode/transformers/ClientTransform.java
- runelite-client/src/main/java/net/runelite/client/rs/bytecode/transformers/ErrorTransform.java
- runelite-client/src/main/java/net/runelite/client/rs/bytecode/transformers/PlayerTransform.java
- runelite-client/src/main/java/net/runelite/client/rs/bytecode/transformers/ProjectileTransform.java
- runelite-client/src/main/java/net/runelite/client/rs/bytecode/transformers/Transform.java
- runelite-mixins/src/main/java/net/runelite/mixins/RSProjectileMixin.java
- runescape-api/src/main/java/net/runelite/rs/api/RSProjectile.java
I personally think the transforms are a lot more readable like this, and it also makes for a nice format to follow, instead of having 10 slightly different codestyles next to each other and try blocks in every method.
The value in getInteracting has to be updated manually, unless we want to add a deob as a dependency
> Cleanup in transforms and add projectile.getInteracting() transform

- runelite-client/src/main/java/net/runelite/client/plugins/alchemicalhydra/HydraPlugin.java
Displays the next poison special indicator with the correct count, even if the last one was with more than 1 poison ball
> Hydra: Fix a poison special bug

- runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/FreezeInfo.java
- runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/FreezeTimersOverlay.java
added in player despawns.
a despawn is counted as:
1) player death
2) player teleports
3) player logs out
4) player runs away from screen
upon triggering 1 of the despawns, the timers will remove themselves for accurate refreezing/appearance
> Freeze additions

- runelite-client/src/main/java/net/runelite/client/menus/AbstractMenuEntry.java
- runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/ShiftClickInputListener.java
- runelite-client/src/main/java/net/runelite/client/plugins/shiftwalker/ShiftWalkerPlugin.java
- runelite-client/src/main/java/net/runelite/client/util/MenuUtil.java
Also switches climb mode back to using priority entries, as that makes it work with shift to walk.
My goal is to basically remove all swap logic from most plugins and instead add it to menumanager. This of course is a lot of work so help appreciated :P
> Add custom menu swaps to menu entry swapper

- runelite-client/src/main/java/net/runelite/client/plugins/tmorph/TMorph.java
Stops
```
java.lang.NullPointerException: null
at net.runelite.client.plugins.tmorph.TMorph.updateEquip(TMorph.java:98)
at net.runelite.client.plugins.tmorph.TMorph.onGameStateChanged(TMorph.java:82)
at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
at net.runelite.client.callback.Hooks.post(Hooks.java:137)
at client.gameStateChanged(client.java:1015)
at jr.fn(jr.java:1189)
at o.hh(o.java:5478)
at client.av(client.java:999)
at bf.aa(bf.java:359)
at bf.run(bf.java:338)
at java.lang.Thread.run(Thread.java:748)
```
> Null check playercomposition for TMorph

- runelite-client/src/main/java/net/runelite/client/plugins/banlist/BanListConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/banlist/BanListPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/banlist/ListType.java
Uses enum instead of int to check list type
Added ability (and config) to highlight scammers name red
> Banlist plugin update

- runelite-client/src/main/java/net/runelite/client/game/ItemManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java
fixes
```
2019-05-31 17:08:55 [pool-2-thread-1] WARN  n.r.c.util.RunnableExceptionLogger - Uncaught exception in runnable net.runelite.client.plugins.examine.ExaminePlugin$$Lambda$1053/1393675677@1d40de09
java.lang.AssertionError: getItemComposition must be called on client thread
at net.runelite.client.game.ItemManager.getItemComposition(ItemManager.java:478)
at net.runelite.client.game.ItemManager.getAlchValue(ItemManager.java:426)
at net.runelite.client.plugins.examine.ExaminePlugin.getItemPrice(ExaminePlugin.java:325)
at net.runelite.client.plugins.examine.ExaminePlugin.lambda$onChatMessage$0(ExaminePlugin.java:212)
at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at …
```
> Make examineplugin stop running getItemComposition on executor thread

- runelite-client/src/main/java/net/runelite/client/plugins/blackjack/BlackjackPlugin.java
Fixes #363
- Don't utilize MenuManager's priority methods and instead only swap
- Originally this did clean up the menu more when right clicking, but if you're using this plugin, you're only left clicking so there doesn't seem to be any point. I believe this is what caused issue #363.
- Don't utilize onGameTick event
- Add region checking to avoid unnecessary calls
> Update Blackjack Plugin

- runelite-mixins/src/main/java/net/runelite/mixins/RSSceneMixin.java
GPU plugin was required to be enabled for clicking with a detached camera or Oculus orb, this fixes that
> Removed GPU requirement for clicking in detached/Oculus state

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/pvptools/AttackMode.java
- runelite-client/src/main/java/net/runelite/client/plugins/pvptools/PvpToolsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/pvptools/PvpToolsPlugin.java
Moves cast and attack being hidden from right click menu to pvptools from menuentryswapper and adds a config option. Also fixes bug when two swaps would interfere with each other.
> Pvpfix - attack/cast

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Adds info messages to replace NPE's created by being unable to load any local loot tracker records
> Prevents Loot Tracker from causing a NullPointer Exception on first run

- runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java
A toggle for right-click-only option tooltips has been added to MouseHighlightConfig
> Updated Mouse Highlight Plugin - Fixed right click tool tips

- runelite-client/src/main/java/net/runelite/client/plugins/metronome/MetronomePlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/metronome/MetronomePluginConfiguration.java
Add custom sound file support (short .wav only)
Add offset option (for aligning tock sounds with in-game events on a cycle)
Add independent volume control for custom sounds
Add option to configure the number of "ticks" between each "tock"
Still uses the previous method if no valid custom sound file is provided.
Example of good custom tick/tock sounds[ here.](https://www.mediafire.com/file/wkfretg0lqoyw4n/Tick+Tock+Meme+Compilation.zip)
> Updated Metronome Plugin - aka its useful now

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Fixes  #521
Made the swap actually work and moved the claim swap up to be higher priority than the trade swap.
> Fix  #521 "Menu Entry Swapper - Claim Dynamite -Broken"

- runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java
Currently, turning off both "Enhance scouter title" and "Show last scavs for Ice Demon" at the same time will cause the entire raids overlay to disappear entirely. This should fix that.
> Fix Raids Overlay disappearing when certain unrelated config options were disabled.

- runelite-client/src/main/resources/npc_stats.json
Currently, the wiki scraper has the hitpoints key name as hitpoints1/2/3/4 for challenge mode mobs, this adds an annoying obstacle. But i'm working on it.
For now im just doing
```
if (stats.hitpoints == null)
{
stats.hitpoints = getInt("hitpoints1", variantKey, template);
}
```
which is obviously not the best solution, as it's inaccurate for CM.
> Add temporary fix to NPC_stats

- runelite-client/src/main/java/net/runelite/client/plugins/learntoclick/LearnToClickConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/learntoclick/LearnToClickPlugin.java
Adds the option to remove the world map and special attack orbs to the learn to click plugin.
Saw this requested in the discord a day or two ago
> Adds option to hide orbs to learn to click plugin

- runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java
somehow this config check was missed
> Stopped default red names for non-clan members

- runelite-client/src/main/java/net/runelite/client/plugins/pileindicators/PileIndicatorsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/pileindicators/PileIndicatorsOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/pileindicators/PileIndicatorsPlugin.java
removed all the player piles code that was slapped into the plugin causing travis to break and re-wrote the intended functionality (convex hull check, and text to show if its a player/npc/mixed pile)
some slight cleanup as well
> fixes #696 and adds the intended functionality

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/Parse.java
Any line that starts with // will be ignored, giving you the ability to categorize your custom swaps.
> Ignore comment lines on custom menu entry swapper

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Suggested in #702. 
Whitelist NPCs, and only their drops will be tracked by the Loot Filter.
Blacklist NPCs, and all NPCs except for those on the blacklist will be tracked by the Loot Filter.
> NPC Whitelist and Blacklist options for Loot Filter

- runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/AboveWidgetsOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/BarbarianAssaultConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/BarbarianAssaultPlugin.java
Can confirm removing the wrong attack styles actually works now. Right now it only hides wrong styles for the crystal halberd and dragon claws as that is how it worked before. It would, however, be very easy to allow any weapon to have its wrong styles hidden - if that's something people want.
> barbarianassault: fix remove wrong attack styles and checkstyle

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/util/CharterOption.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/util/teleEquippedMode.java
Supersedes/Closes runelite#7353
Supersedes/Closes runelite#7415
Supersedes/Closes runelite#7493
Supersedes/Closes runelite#7401
Supersedes/Closes runelite#5383
Streamline teleport item swaps
**Pickpock swap no longer limited by just HAM members**
Move Mage of Zamorak teleport to Travel swap
It is a travel swap so there's no reason for it to have it's own option.
Unify bank and exchange options
There's no reason for these to be separate options.
Unify interact options
Grouped generic interactions swaps for NPCs
Unify minigames options
Grouped minigames swaps
Swap Coal Bag Empty 
Makes Empty the left click option when in a bank
Teleport Equipped Cape
Makes Teleport/Tele to POH the left click option on equip screen
'Trade' or 'Charter' as first option
> Updated menu swapper

- runelite-api/src/main/java/net/runelite/api/coords/WorldArea.java
- runelite-client/src/main/java/net/runelite/client/plugins/npcstatus/MemorizedNPC.java
- runelite-client/src/main/java/net/runelite/client/plugins/npcstatus/NpcStatusConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/npcstatus/NpcStatusOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/npcstatus/NpcStatusPlugin.java
The new function is for determining if it's possible to do a melee
attack between 2 actors of which the WorldArea are given. This checks
for melee distance AND for collision. That new function is used in
the npcstatus plugin.
The npcstatus plugin requires the attackrate and attackrange of an npc
as input, and returns a timer on the npc when they either are targetting
you or you are targetting them. With only the given input, the plugin is
able to determine when an npc will/can attack, when the npc can't be
flinched, when the npc can be flinched, and the duration of the flinch.
Timer info:
Orange: counter for when the npc is able to attack again. The timer is
caused by getting attacked by the npc.
Red: counter for when the npc will be flinchable again, assuming the
player won't get hit by …
> Add a new function to the WorldArea api. Add npcstatus plugin.

- runelite-client/src/main/java/net/runelite/client/graphics/ModelOutlineRenderer.java
Model can never be null here, it was caused by the NpcDespawnEvent that wasn't firing
> Remove this band aid 'fix'

- runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/BarbarianAssaultMenu.java
- runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/Menus.java
Made hidden entries more specific so that they only applies to horns available in barbarian assault and rechecked the list of hidden entries to make sure this wouldn't happen with anything else.
Fixes issue #848
> barbarianassault: fix horn hidden entry hiding non ba items

- runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
- runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
Not sure what the current plan with menumanager is, feel free to close the pr if there is something else planned or if it's changing too much. 
This changes menu manager a decent amount as to how it works. There are noticeable performance improvements from these changes (from 20-30 fps in world 2 GE with 400 menu options to a consistent 40 fps.) The priority entry system has been changed to show the unprioritized entries under the prioritized ones, rather than clearing the menu and only showing the priority entries. This allows for plugins like tiles markers to still function while a plugin like shift to walk is enabled. This also fixes custom swaps with low id's not working.
Note: If there are multiple swaps in the same menu only the first one found will be applied, it'd take 10 seconds …
> menumanager: more menu fixes

- runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsBrotherSlainOverlay.java
Accurately apply red color to X (brothers not killed yet) and green color to ✓ (brother has been killed)
> Fix Barrows overlay colors

- http-api/src/main/java/net/runelite/http/api/RuneLiteAPI.java
- pom.xml
Updated okhttp3 from 3.7.0 to okhttp3 4.0.0
Added timeout stuff
Tested on my fast connection, !price seems faster/less/no microstutter
Needs to be tested on a slow connection, justin was talking about how he had a firewall and it would freeze his client for 15 seconds. Maybe he can test.
> runeliteapi: add timeout to rlp api call.

- runelite-client/src/main/java/net/runelite/client/plugins/pluginsorter/PluginSorterPlugin.java
> pluginsorter: fix runelite plugin incorrect position when unhiding plugins

- runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
@tomcylke was getting a [NoSuchElementException](https://gyazo.com/0b34afc80add6800dd74ad0c97bccb85) because Google's Iterables class throws an exception when you call getLast() with an emply list as the parameter, unless you include a default value.
It now has a default value of null, which is the correct value it should be if the list is empty.
> menumanager: fix NoElementException

- runelite-client/src/main/java/net/runelite/client/util/ItemFinder.java
Various plugins behave differently depending on what you have in your inventory or equipped. Rather than every plugin scanning the inventory constantly, it'd be good if there was a single system doing it. 
right now every plugin will still be calling this class every tick so it's not ideal performance-wise; but it at least reduces code duplication
> Add ItemFinder util

- runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
The left click entry was being cleared every time an option was clicked, but because the left click menu is being built before each render instead of every time an entry is added to the menu, if you clicked more than once per render the second click would not be swapped. This changes it so that the menu is also rebuilt every click to fix slow swaps.
Fixes #819
Examples:
[Before fix](https://gyazo.com/79a1d030b4456de24f01b63e61638e28)
[After fix](https://gyazo.com/8126435ff97eba4322186b085c9e8aad)
> menumanager: fix slow swaps

- runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
Murphy's law appears to be working its magic. I'm just fixing the bugs as they come up, hopefully this is the last one.
The problem with this one was that hidden entries were never actually being removed from the left click menu. Fixes barbarian assault horn not having correct left click option and fixes hidden entries in general.
> menumanager: fix hidden entries

- runelite-api/src/main/java/net/runelite/api/events/MenuOptionClicked.java
- runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
- runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
- runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
MenuManager was intercepting all clicks and setting what it should be after hiding/prioritizing/swapping entries in the current menu, this works fine unless another plugin invokes a menuaction such as the world hopper plugin, or an external plugin. This pr adds a flag to MenuOptionClicked events allowing MenuManager to differentiate between authentic clicks and invoked clicks.
Fixes #906
> menuentryclicked: add isauthentic field

- runelite-client/src/main/java/net/runelite/client/plugins/safespot/SafeSpotPlugin.java
Before this, you could for example get this bug:
Have player safespots turned on and NPC safespots turned off.
Interact with another player, which creates a safespotlist.
After this, whenever you're interacting with an NPC and then stop
interacting with it, the overlay would turn on with the tiles from the
old playerinteraction safespotlist rendered for 10 ticks.
> safespot: stops the safespot overlay from rendering when it's not supposed to.

- runelite-api/src/main/java/net/runelite/api/events/WidgetPressed.java
- runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
- runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
- runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
- runescape-api/src/main/java/net/runelite/rs/api/RSMenuAction.java
Fixes issue where the left click entry would not be correct for inventory items.
[Example of Issue](https://gyazo.com/a7b74fa2f61381272c8ff1c059b38433)
Cause: This was being happening because the `MenuOptionClicked` event does not post for draggable widgets (such as inventory items) until after the mouse is released. Because the left click menu was being built during that event, the new menu would be built based off of menu at the time of release. This caused swapped/prioritized entries to not be properly accounted for if the mouse was not over the same item pressed when released.
Fix: The left click entry is now set when a `WidgetPressed` event is posted, which posts when draggable widgets are clicked. If no `WidgetPressed` event is posted because a non draggable widget was clicked, the …
>  menumanager: fix inaccurate left click options for inventory items

- runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
- runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
I have updated the posting of menuentryadded to use the correct type/identifier parameters. I'm slowly working through the plugins that use menuentryadded which is I think 30 or so plugins. I'll push commits as I verify that they are working. If you know of any specific plugins that were changed to "fix" them please save me some time looking through the previous commits and let me know.
Edit: I went through the commit history and narrowed down the list of possibly affected plugins to the following:
> menuentryadded: fix incorrect type/identifier

- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
Type/Identifiers were switched back so this fix should be reverted.
> grounditems: revert "Fix ground item menu color"

- runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridOverlay.java
The way it was being done before was the correct way, this commit https://github.com/runelite-extended/runelite/commit/d6285235cb836d90c09dae22e686a113bef88c4d actually broke it. So this reverts it back to the original method.
Closes #974
> Inventory Grid Plugin: Make it so the grid/background actually works

- runelite-client/src/main/java/net/runelite/client/plugins/npcstatus/MemorizedNPC.java
- runelite-client/src/main/java/net/runelite/client/plugins/npcstatus/NpcStatusConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/npcstatus/NpcStatusOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/npcstatus/NpcStatusPlugin.java
Implement optional custom attack speed as config option, useful because the npc
stats data we have from wiki isn't 100% correct, or isn't even there sometimes.
Add minimum attackrange of 1.
Render timer when the player is interacting with an NPC.
Add default attack speed of 4 when wiki doesn't provide the data.
Fix splash flinching while using a better method to implement it, using
the function "onSpotAnimationChanged".
Remove deprecated variable "lastspotanimation".
Remove unused variable "lastTickUpdate".
> npcstatus: Add custom attack speed option. Some fixes/improvements.

- runelite-client/src/main/java/net/runelite/client/plugins/statusorbs/StatusOrbsOverlay.java
Owain broke the overlay on the run energy orb by adding an extra if to the logic where it wasn't really needed so that it only ended up showing the overlay when the `run time left` option was enabled. This fixes it back to how it was originally where it always shows the overlay whenever you mouse over the run energy orb (how it was with the runenergy plugin).
Tried to make indentation look like the rest, but if it's wrong let me know and I'll try to fix it (or you can fix it if you want since I allow edits from maintainers). I've tried several things to remove the new line at the EOF that's being created but for some reason github is being dumb and not removing it..
> Status Orb Plugin: Fix run energy overlay

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
was missing  alanbaumgartner's copyright when porting easyscape to menu entry swapper.
licence info now added & correct copyright date(s) amended too.
> menu entry swapper: Licence addition

- cache/src/main/java/net/runelite/cache/io/OutputStream.java
Fixes a maven compilation error when using Oracles jdk 1.8u211/1.8u212.
`[ERROR] Failed to execute goal net.runelite:script-assembler-plugin:1.5.29-SNAPSHOT:assemble (assemble) on project client: Execution assemble of goal net.runelite:script-assembler-plugin:1.5.29-SNAPSHOT:assemble failed: An API incompatibility was encountered while executing net.runelite:script-assembler-plugin:1.5.29-SNAPSHOT:assemble: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;`
> cache: Cast ByteBuffer to Buffer to avoid compilation error with jdk 1.8u211

- runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragConfig.java
would hide the config option to change the drag delay when using always-on mode
> Fixes small anti-drag config bug

- runelite-client/src/main/java/net/runelite/client/game/ItemManager.java
- runelite-client/src/main/java/net/runelite/client/game/PvPValueBrokenItem.java
- runelite-client/src/main/java/net/runelite/client/plugins/playerscouter/AttackStyle.java
- runelite-client/src/main/java/net/runelite/client/plugins/playerscouter/AttackerOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/playerscouter/PlayerContainer.java
- runelite-client/src/main/java/net/runelite/client/plugins/playerscouter/PlayerScouter.java
- runelite-client/src/main/java/net/runelite/client/plugins/playerscouter/PlayerScouterConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/playerscouter/Utils.java
**Green = Low Risk**
**Blue = Med Risk**
**Orange = High Risk**
**On the top left icon you have the players most valuable piece of equipment,
regardless of risk.
On the top right If the player is skulled they will appear with a skull icon on the webhook,
else it will be their main weapon.**
On a side note, there is a lot more information being scraped here in case we plan to expand the scouter in the future, for example accurate prayer predictions, or attack styles and weaknesses.
> playerscouter: adds a discord-webhook based Player Scouter

- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/MemorizedNpc.java
- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcMinimapOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java
Adds 2 new functions to NPC Indicators involving Interacting of NPCs.
Have the name of the currently aggro'd Actor of a marked npc displayed above its head, if name config is on the position of the target name will adjust accordingly:
https://i.imgur.com/1Ml7RE5.gifv
https://i.imgur.com/qVRly3e.gifv
Have the colour of the NPC Highlight change to the colour in config if the marked NPC is currently targeting you:
https://i.imgur.com/EKrynnl.gifv
> npcindicators: add Interacting functionality

- runelite-client/src/main/java/net/runelite/client/plugins/privateserver/PrivateServerPlugin.java
rsa mismatches were still possible even when not using --rs=RSPS.
> private-server: enforce osrs key if rs!=RSPS

- runelite-client/src/main/java/net/runelite/client/plugins/boosts/CombatIconsOverlay.java
Not sure exactly why this broke but setting the gap fixes it
> boosts: Separate icons so they aren't stacked

- runelite-api/src/main/java/net/runelite/api/events/PlayerDeath.java
- runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
- runelite-mixins/src/main/java/net/runelite/mixins/RSActorMixin.java
using the LocalPlayerDeath and PlayerDeath events captures the screenshot with the killing hit splat still showing rather than just the player in the death animation.
> screenshot: use playerdeath events

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Prevents left click on the inventory widget from opening the configure shift click menu.
> menuentryswapper: Prevent Left Click Configure Shift-Click

- build.gradle
- injected-client/src/main/java/Placeholder.java
- injector-plugin/src/main/java/net/runelite/injector/Injector.java
- runelite-client/build.gradle
- runelite-client/src/main/java/net/runelite/client/rs/ClientLoader.java
This fixes the `upload` task so when deploying `injected-client` it will deploy the build result instead of an empty jar file.
> gradle: partially revert #1166

- runelite-client/src/main/java/net/runelite/client/plugins/raidsthieving/BatSolver/ThievingRoomType.java
- runelite-client/src/main/java/net/runelite/client/plugins/raidsthieving/RaidsThievingPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/raidsthieving/ThievingChest.java
re add and use the original world point conversion methods to account for thieving rooms rotation currently only one rotation of each type of thieving room works unluckily the room i tested for the last pr was one of the working rotations so this slipped by.
> raidsthieving: ignore room rotation

- runelite-client/src/main/java/net/runelite/client/plugins/pluginsorter/PluginSorterConfig.java
pluginsorter: pastel colorscheme
some users were complaining the colorscheme hurt there eyes.
changed colorscheme to a pastel colorscheme which is alot easier on the eyes.
> pluginsorter: pastel colorscheme

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Swaps were not being cleared correctly, needed an extra removePriorityEntry to make it work as intended.
> menuentryswapper: Fix Swaps for Coal Bag

- runelite-client/src/main/java/net/runelite/client/plugins/multiindicators/MultiIndicatorsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/multiindicators/MultiIndicatorsMinimapOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/multiindicators/MultiIndicatorsPlugin.java
removes the scheduled method that updated the lines every 1.8s and updates them on clientthread now. seems to have fixed the lag/fps spike that would happen after leaving client open for long time/hopping worlds.
adds clipping for lines rendered on minimap
need to eventually refactor multilines plugin and maybe make it use world locations
> multilines: fix bug that caused lag/fps spikes after leaving client open and hopping lots of worlds

- build.gradle
Provides better compatibility with /bin/sh, /bin/bash and the likes, which don't accept env vars with dashes in the name.
> gradle: update env vars to use underscores

- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java
Seems a bit dark in most environments, making text illegible in some circumstances. I also happen to like the pastel colors we've been moving to.
> grounditems: lighten default highlight color

- runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/SotetsegHandler.java
The soteyProjectiles.clear() is not required and clears the Projectiles before they are rendered.
> theatre: remove unnecessary reset.

- runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
All the config options do save when they are changed except for the
textarea (aka string) settings. This will add a Document listener to the
textarea with a debounce of 350ms, after the debounce the config option
will be saved
> config: Save textareas on debounce instead of on focus lost

- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java
https://github.com/runelite-extended/runelite/commit/86ad4d9d2df2104ed2846d34b858f66b6dd9030d removed the checkSpots method (assumedly as it initially appears unused) but as it is annotated with Schedule, it is required for cannon placement spots to display.
> cannonplugin: fix issue with cannon spots not displaying

- runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
Supersedes #1409 
Closes #1406 
Had to cherry-pick commits to clean up history because it's meant to be `&&`, and I'm an idiot. Sorry @Netami1
> add null check guard case for chat message manager

- runelite-client/src/main/java/net/runelite/client/plugins/playerscouter/PlayerScouter.java
- runelite-client/src/main/java/net/runelite/client/plugins/playerscouter/PlayerScouterConfig.java
add a searchable combat bracket for the player scouter.
stress tested by @Crystalknoct.
in W302 GE, FPS dropped to 30, in medium populated area's and other worlds, solid 50 FPS.
> Playerscouter: add combat bracket

- runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java
removes the pvp hop-to restriction from a normal world.
been requested alot by pure and main clans as its very annoying when clanning / singles pking and you cant right/left click hop-to whilst in CC or via friends list if in a non PVP world..
just to confirm, the WARNING that you're hopping to a PVP world is still active to avoid luring/scamming.
> Worldhopper: pvp hop restriction

- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
Highlights items that could provide you with Herblore / Prayer XP.
Value is still prioritized over XP.
This includes:
```
Herblore:
Grimy Herbs
Clean Herbs
Secondary ingredients
Jungle Potion herbs
Herb seeds
Secondary seeds
Prayer:
Bones
Ensouled heads
```
All noted items should count as well.
Below is an example
> grounditems: highlight herblore / prayer ground items

- runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsService.java
Adds friendly priority to targets so they will be highlighted as friends/clan/team/callers/piles before being highlighted as a target
> playerindicators: prioritize clan and friends over targets

- runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/PlayerSpellEffect.java
removed the half effect from freezetimers for bind, snare and entangle ready for tomorrows integrity update.
> freezetimers: update standard timers

- runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java
closes #1516 
Added a spacer of 10px if combat level is enabled to prevent the icon being squished.
> playerindicators: fix agility icon spacing

- runelite-client/src/main/java/net/runelite/client/config/ConfigInvocationHandler.java
Closes #1518
This adds back #455
> configinvocationhandler: Set config to default if string to object fails and it's a default method

- runelite-api/src/main/java/net/runelite/api/Client.java
- runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderPlugin.java
- runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderBridgeMixin.java
- runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderMixin.java
Changes Entity Hider to keep track of how many plugins wish to hide an entity, only unhiding it once all plugins have released their locks.
> npchider: change method by which npcs are hidden by name

- build.gradle
- injector-plugin/build.gradle
- runescape-api/build.gradle
- runescape-client/build.gradle
Changes namespace so maven doesn't pull other things we don't want it to.
> project: change namespace

- runelite-api/src/main/java/net/runelite/api/Actor.java
- runelite-client/src/main/java/net/runelite/client/graphics/ModelOutlineRenderer.java
- runescape-api/src/main/java/net/runelite/rs/api/RSActor.java
Orientation lags behind most of the times while rotation doesn't
> modeloutline: Use rotation instead of orientation

- runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
"FSCCS.PCPSF - #WSEEEN#WSWNWS"
This layout was missing so returning Bad crabs when it should follow the normal rules - bad crabs first good crabs seconds.
> Raids: Add missing layout

- runelite-client/src/main/java/net/runelite/client/plugins/whalewatchers/WhaleWatchersConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/whalewatchers/WhaleWatchersPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/whalewatchers/WhaleWatchersProtOverlay.java
Adds a config option to display only a thin red border instead of the thick red border with large text.
Accidentally misspelled WhaleWatchers in the title of the commit sorry.
> Less Obnoxious WhaleWatchers Overlay 

- runelite-client/src/main/java/net/runelite/client/RuneLite.java
fixes `Discord error: 4000 - child "pid" fails because ["pid" must be larger than or equal to 10]`
doesnt fix party plugin
> discord-service: initialize discord service before starting plugins

- runelite-client/src/main/java/net/runelite/client/plugins/slayermusiq/QuestGuideLinks.java
This adds a working right click > slayermusiq option to the new Fremennik Exiles quest. Action will open up the quest guide on YT.
> slayermusiq: added the fremennik exiles link

- runelite-api/src/main/java/net/runelite/api/Actor.java
- runelite-api/src/main/java/net/runelite/api/Locatable.java
- runelite-api/src/main/java/net/runelite/api/LocatableQueryResults.java
- runelite-api/src/main/java/net/runelite/api/Query.java
- runelite-api/src/main/java/net/runelite/api/QueryResults.java
- runelite-api/src/main/java/net/runelite/api/TileObject.java
- runelite-api/src/main/java/net/runelite/api/queries/ActorQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/BankItemQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/DecorativeObjectQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/DialogQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/EquipmentItemQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/GameObjectQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/GroundObjectQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/InventoryItemQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/InventoryWidgetItemQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/LocatableQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/NPCQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/PlayerQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/ShopItemQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/TileObjectQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/WallObjectQuery.java
- runelite-api/src/main/java/net/runelite/api/queries/WidgetItemQuery.java
An Implementation of Devin French's query system, expanded upon a bit.
This PR allows for querying of various entities in Runelite such as:
- NPCs
- Game Objects
- Dialog
- Equipment
- Inventory Items
- Players
- Shop Items
- And more
Example Query:
`new NPCQuery().nameContains("Fishing spot").result(client).nearestTo(client.getLocalPlayer());`
This is meant to be a foundation for a framework, as new commonly methods are thought up, they can be added to the various `QueryResult` classes.
To be improved:
Caching should probably be implemented at some point
Dialog querying only supports a limited selection of dialog types, this can be expanded upon
> api: add devin's query system back in for niche uses.

- runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/CoxPlugin.java
sanitize player name for non-breaking spaces
add null check player name
closes #1626
> coxhelper: fix teleport timers for names with spaces

- runelite-api/src/main/java/net/runelite/api/events/MenuEntryAdded.java
- runelite-api/src/main/java/net/runelite/api/events/MenuOpened.java
- runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/chattranslation/ChatTranslationPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/corp/CorpPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
- runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
This was causing a bug with agility plugin undoing other plugins' modifications to menuOpened events' menuentries if it started after the other plugin
> api: Change menu events' setModifed so it can't change modified back to false

- runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/CoxPlugin.java
Sanitize the Regex match result since it still has nbsp in it.
> coxhelper: fix teleport targets with spaces

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Removes line 605 of `MenuEntrySwapperPlugin.java`, which is as follows:
`targetLength > object.length() && target.startsWith(object))`
Previously if you added `Tree` to the `Remove objects` list, it will also remove `Tree Door`, `Tree Trunk`, or anything else that starts with `Tree`. This is meant to fix that. Build tested and working as expected.
Screenshot of previous bug:
https://whocodes.tech/upload/javaw_Qm7U0hkuxq.png
> menuentryswapper: Fix Remove objects wildcard

- runelite-client/src/main/java/net/runelite/client/plugins/deathindicator/Bones.java
- runelite-client/src/main/java/net/runelite/client/plugins/deathindicator/DeathIndicatorPlugin.java
Fixes a NotSupportedOperationException when someone dies in a region which didn't have any boners yet
Also moves a useless debug message from debug to trace
> deathindicators: Fix saving bones to config

- runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java
When the plugin was re-implemented, the logic was copied incorrectly, you can see the original here: https://github.com/runelite-extended/runelite/commit/39fd5f6bacf2e926fc1746ec280cf99bb8b98b44#diff-07e1c0eea1fac0994278c3d53423df06R251-R276
As it is written currently, it never shows the second agility icon that should be shown when the second threshold is met
> playerindicators: Fix agility overhead icons

- runelite-api/src/main/java/net/runelite/api/coords/WorldPoint.java
- runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/deathindicator/Bones.java
- runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/hideunder/HideUnder.java
- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/maxhit/calculators/MagicMaxHitCalculator.java
- runelite-client/src/main/java/net/runelite/client/plugins/metronome/MetronomePlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/theatre/rooms/MaidenHandler.java
- runelite-client/src/main/java/net/runelite/client/plugins/tobdamagecount/DamageCounterPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/vorkath/VorkathPlugin.java
Closes #1667
Closes #1949
Closes #1951
Closes #1959
Closes #1966
Closes #1973
Closes #1974
Closes #1977
Closes #1978
Closes #1981
Closes #1983
Still more to come.
> project: bug fixes

- runelite-client/src/main/java/net/runelite/client/plugins/spellbook/SpellbookPlugin.java
> spellbook: StringIndexOutOfBoundsException and ArithmeticException

- injected-client/injected-client.gradle.kts
As a brand new project, every configuration I tried (including disabling configure on demand, parallel, and caching) resulted in Injection failing because rs-client and mixins jars hadn't been built yet. Enforcing the dependency solved the problem.
@Owain94
> project: ensure injector deps are built

- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
Fixes issue #670 by taking into account the quantity of the **stack**. This does not have an affect on non-stacked items.
> Client: Account for quantity of ground item when deciding to hide item from left-click

- runelite-client/src/main/java/net/runelite/client/plugins/learntoclick/LearnToClickPlugin.java
The plugin now correctly sets the world map orb/xp drop toggle as right click only if the config options are selected.
> learntoclick: fix world map and xp drops

- runelite-client/src/main/java/net/runelite/client/RuneLite.java
- runelite-client/src/main/java/net/runelite/client/plugins/info/InfoConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPlugin.java
new info added:
1) Launcher download
2) Runelite DIR
3) Plugins DIR
4) Screenshots DIR
updated:
1) Discord link to vanity URL.
2) Github licence updated to new github.
physical path details:
1) Runelite Directory
2) Log Directory
3) Plugins Directory
4) Screenshot Directory
added config options to turn on/off:
1) Show the Github info.
2) Show the Launcher info.
3) show the Log Directory.
4) Show the Runelite Directory.
5) Show the Plugins Directory.
6) Show the Screenshot Directory.
6) Show the Physical Directory information.
> Info: new info

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Change MES Impling swaps to remove just the loot / use swap instead of removing all swaps which effects trying to add custom swaps/bank swaps
made new PR cos I lost the old branch
> menuentryswapper: implings remove only loot/use swap

- runelite-client/src/main/java/net/runelite/client/plugins/gauntlet/GauntletPlugin.java
Fix double resource counter and resource counter starting at 1
onXpDrop event fires off twice each xp gain.
Switched to onStatsChanged with checks added to make sure player is in gauntlet and resets when entered
> GauntletPlugin: Resource fix

- buildSrc/src/main/kotlin/BootstrapTask.kt
bootstrap fix.
injection annotation now uses the GH raw jar instead of trying to go via the maven repo.
> bootstrap: fix

- runescape-client/src/main/java/BZip2Decompressor.java
Hi there!
I've been trying to launch the compiled `runescape-client` with my own applet loader and got this exception:
```java.lang.NegativeArraySizeException: -1530494976
at BZip2Decompressor.BZip2Decompressor_decompress(BZip2Decompressor.java:197)
at BZip2Decompressor.BZip2Decompressor_decompress(BZip2Decompressor.java:33)
at Skills.decompressBytes(Skills.java:51)
at AbstractArchive.decodeIndex(AbstractArchive.java:100)
at Archive.write(Archive.java:184)
at Client.doCycleJs5(Client.java:2611)
at Client.doCycle(Client.java:1624)
at GameShell.clientTick(GameShell.java:588)
at GameShell.run(GameShell.java:916)
at java.base/java.lang.Thread.run(Thread.java:830)
```
I compared the code with a previously decompiled version and discovered that this constant should be set to `1`. Now everything …
> Client: Fix skill unpacking during bootstrap

- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/RenderStyle.java
Adds a config option to render the tile with width 1 instead of width 2.
> npchighlight: thin tile overlay

- runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsPlugin.java
When this option is enabled, status bars were only hidden after entering and leaving combat for the first time. This change allows the status bars to be correctly hidden without requiring entering then leaving combat.
> StatusBars: Fix hide when our of combat ignored until first combat

- runelite-client/src/main/java/net/runelite/client/plugins/stealingartefacts/StealingArtefactsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/stealingartefacts/StealingArtefactsHouse.java
- runelite-client/src/main/java/net/runelite/client/plugins/stealingartefacts/StealingArtefactsInfoBox.java
- runelite-client/src/main/java/net/runelite/client/plugins/stealingartefacts/StealingArtefactsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/stealingartefacts/StealingArtefactsWorldMapPoint.java
Features
- An InfoBox indicating the artefact location
- A HintArrow and WorldMapPoint indicating the artefact location
Not sure how popular the Stealing Artefacts minigame is in the main game, but this plugin will be very useful for anyone playing Twisted League.
> Plugin: Stealing Artefacts

- runelite-client/runelite-client.gradle.kts
runelite-api is a dependency of http-api. so we will use api instead of implementation.
> gradle: use transitive rl-api dep

- runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java
xpdrop: remove twisted league multiplier
> xpdrop: remove twisted league multiplier

- buildSrc/src/main/kotlin/BootstrapPlugin.kt
Before, it was ignoring injected-client, now it will not.
> project: publish all deps when bootstrapping

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
This isn't really a full on fix, a better option would be to have a new comparable entry specifically for trading, similar to the withdraws and it'd have to compare with a standardized string. This however works for most use cases and is easy to implement.
Path of least resistance and all.
> mes: add an option to swap offer-all

- http-api/src/main/java/net/runelite/http/api/worlds/WorldClient.java
```
2020-02-01 01:05:33 [pool-4-thread-1] WARN  n.runelite.client.game.WorldService - Error looking up worlds
java.io.IOException: com.google.gson.JsonIOException: java.io.IOException: failed to delete C:\Users\User\.runelite\cache\okhttp\b0c59f847558d67b40e6822c8b5f6d1f.1
at net.runelite.http.api.worlds.WorldClient.lookupWorlds(WorldClient.java:78)
at net.runelite.client.game.WorldService.fetch(WorldService.java:94)
at net.runelite.client.game.WorldService.tick(WorldService.java:79)
at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$Schedu …
```
> WorldClient: Force Http Request to ignore local OkHttp cache

- .github/ISSUE_TEMPLATE/Bug_report.md
Change RuneLite -> OpenOSRS and change example version numbers.
Version numbers are one out-of-date on purpose to avoid misleading situations where people just copy the example.
> github: change bug report template

- runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListPanel.java
java.lang.NullPointerException: null
at net.runelite.client.plugins.config.PluginListPanel.lambda$new$3(PluginListPanel.java:179)
at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
at io.reactivex.rxjava3.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onNext(ObservableDoFinally.java:80)
at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:63)
at io.reactivex.rxjava3.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
at com.jakewharton.rxrelay3.PublishRelay$PublishDisposable.onNext(PublishRelay.java:179)
at com.jakewharton.rxrelay3.PublishRelay.accept(PublishRelay.java:144)
at com.jakewharton.rxrelay3.SerializedRelay.accept(SerializedRel …
> pluginlist: Add null check

- runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
Reverts open-osrs/runelite#2552
The original PR broke:
::toggleroof
::displayfps
::renderself
::mouseovertext
Also the title was completely wrong?
> Revert "project: add groovy dependency"

- runelite-client/src/main/java/net/runelite/client/RuneLiteProperties.java
- runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListItem.java
Enables the pf4j [development mode](https://pf4j.org/doc/development-mode.html)
to support loading external plugins from sources, which enables java's
hotswap functionality.
To use this feature set the `plugin.development.path` property or
`PLUGIN_DEVELOPMENT_PATH` environment variable to the directories
containing your plugins, e.g. `../plugins;../my-custom-plugins`
Once set the `ExternalPluginManager` will ignore the configured
repositories and externalmanager directory, and instead load all
the built plugins from the specified directories.
Utilizing this feature does require some additional configuration
of the build of the plugins `build.gradle.kts`. Within the `subprojects`
section add:
```
tasks.register<Copy>("copyDeps") {
into("./build/deps/") …
```
> Client: Support loading external plugins from sources enabling hotswapping

- runelite-client/src/main/java/net/runelite/client/config/OpenOSRSConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/ExternalPf4jPluginManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginClasspath.java
- runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginFileFilter.java
- runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListItem.java
This PR refactors the `ExternalPluginManager` extracting some subclasses to their own files, as it was getting quite big.
I've also moved some variables to constants and fixed a bug where repositories could get loaded multiple times, since `tryLoadNewFormat` did not clear the repository list prior to invocation (`loadOldFormat` did though), and some code paths could invoke it multiple times.
Some logging has also been changed to provide more helpful messages.
> client: Clean up ExternalPluginManager & friends

- runelite-client/src/main/java/net/runelite/client/plugins/ExternalPf4jPluginManager.java
The default pf4j comparator casts longs to ints which breaks
the sort. Since we don't actually rely on this sorting, simply
set the comparator to `null`.
See https://github.com/open-osrs/runelite/pull/2621 for more info
> client: Set JarPluginRepository#comparator to null

- runelite-client/src/main/java/net/runelite/client/config/OpenOSRSConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListPanel.java
Adds the option to sort plugins by their repository provider. Only does it in Categories because I couldn't find a solid way to sort it in this manner without Categories. The try/catch when getting the plugin provider is because some plugins do not have a provider, and are therefore given the "Default" category. 
For #2651
> Plugin-Panel: Add sorting plugins by repository

- runelite-client/runelite-client.gradle.kts
- runelite-script-assembler-plugin/runelite-script-assembler-plugin.gradle.kts
- runelite-script-assembler-plugin/src/main/java/net/runelite/script/AssembleMojo.java
Also have assembler scripts be output into build directory.
Partially fixes #2665, though it's still a hack to use JavaExec like this. But turning it into a proper plugin requires splitting it out of the module build afaik, and that is a pain because it depends on the cache module.
> client: Add inputs & output definitions to script assembler plugin

- runelite-client/src/main/java/net/runelite/client/RuneLiteModule.java
- runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java
- runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
- runelite-client/src/main/java/net/runelite/client/util/NonScheduledExecutorServiceExceptionLogger.java
- runelite-client/src/test/java/net/runelite/client/plugins/PluginManagerTest.java
The new ExecutorService is configured to consume up to 2*CPU threads
and will queue tasks when all threads are busy. Threads are created
as needed, and will be disposed of after 1 minute of inactivity.
> client: Provide a scaling ExecutorService and use it from plugin managers

- runelite-client/src/main/java/net/runelite/client/game/PlayerContainer.java
- runelite-client/src/main/java/net/runelite/client/game/PlayerManager.java
Makes it slightly less janky. It should still be modified to not have it's own executor. Just using the standard one is a bad solution though, because it's blocking io AND because it blocks the thread it's on for up to 10 http requests + 9000ms of sleeping. I also don't like how it doesn't communicate the state of rate-limited-ness to not keep spamming jamflex
> playermanager: Ensure no duplicate hiscore lookups are performed (and cleanup)

- runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
Should have done this with the last one, but tunnel vision.
> rl-api: fix the rest of the incorrect equip-your-char widgets

- runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListPanel.java
This fixes a long standing problem.
On first time startup for OPRS, pluginList will return null, and plugins installed during that first bootup will no longer update in the list.
Requiring every single new user to restart the client at least once before using any new plugins.
> client: fix first time bootup failure

- runelite-client/src/main/java/net/runelite/client/plugins/ExternalPf4jPluginManager.java
This displays a prompt alerting the user that they have duplicate plugins, and a failure to delete them will result in a degraded client experience.
> externalmanager: alert user when they have duplicate plugins.

- runelite-api/src/main/java/net/runelite/api/Client.java
- runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
- runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
These are useful for testing purposes and they will make it easier to add missing game states to the GameState.java enum
> api: getRSGameState and setRSGameState functions

- build.gradle.kts
Grgit fails when the project is a submodule. See https://github.com/ajoberstar/grgit/issues/80.
You can reproduce this by trying to build the project as a submodule. We'd get an _Access is denied_ error.
Further, if you search the Discord for _access is denied_, you'll find similar issues for this line. I doubt everybody is using submodules, but the cause of the error is evidently grgit. The error likely comes from expecting a file with executable permissions (like a directory), but finding a plaintext file (like in the case of a submodule).
This PR catches any errors and falls back to just shelling out and running `git rev-parse HEAD` instead. I abstract this functionality to a new `Utilities.kt` file in the `buildSrc` dir.
Alternatively, I propose we just remove the grgit library …
> gradle: catch grgit errors

- runelite-mixins/src/main/java/net/runelite/mixins/KeyPressedMixin.java
- runelite-mixins/src/main/java/net/runelite/mixins/RSDynamicObjectMixin.java
- runelite-mixins/src/main/java/net/runelite/mixins/RSSequenceDefinitionMixin.java
- runescape-api/src/main/java/net/runelite/rs/api/RSDynamicObject.java
- runescape-api/src/main/java/net/runelite/rs/api/RSSequenceDefinition.java
We don't need to keep the `animationId` field around in DynamicObject, we can instead access the tag of the SequenceDefinition to get the animation id, preventing any potential confusion in future. Also fixes a typo in the sequence definition mixin and rsapi files, and renames KeyHandlerMixin to not conflict with an rs-client class, removing more potential confusion.
> mixins: simplify dynamic object and sequence definition mixins

- runelite-client/src/main/java/net/runelite/client/plugins/ExternalPf4jPluginManager.java
This bug has been fixed upstream. Removing this line saves us from having to override changed functions in the new pf4j release
> externalmanager: Comparator

- http-api/src/main/java/net/runelite/http/api/RuneLiteAPI.java
As of now runelite doesnt support this link:
https://api.runelite.net/runelite-1.6.33-SNAPSHOT/worlds.js
When ignoring the SNAPSHOT version it takes the heighest version which isnt a snapshot.
> HTTP-API: Ignore snapshots for the runelite API.

- runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
The event can modify the action, so we print what the action is after the event fires.
> mixins: move menuaction print to after event

- runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
A lot of plugins put all of their configuration into one file, making for very large files.
I'd like to break up my configuration to avoid these large files, e.g. in Kotlin:
```
@ConfigGroup("my.config.group")
interface MyConfig : MyConfigA, MyConfigB, Config {
@JvmDefault
@ConfigItem(...)
fun hello() = ...
}
interface MyConfigA {
@JvmDefault
@ConfigItem(...)
fun a() = ...
}
interface MyConfigB {
@JvmDefault
@ConfigItem(...)
fun b() = ...
}
```
The above example actually works fine for simple types. Any default values not written to the properties file would just be written later on when you'd change them. However, enumerations are a different story because of the [following line in ConfigPanel.java](https://github.com/open-osrs/runelite/blob/64da9b0ed1e3f4641b6ab55a336d1f4cc6ca5885/runeli …
> configmanager: write all of our config items to our properties

- runelite-client/src/main/java/net/runelite/client/plugins/ExternalPf4jPluginManager.java
When loading plugins in the default order, lets say
Wintertodt-0.0.1.jar
Wintertodt-0.0.2.jar
Wintertodt-0.0.3.jar
It would load 0.0.1 then detect 0.0.2 and 0.0.3 as duplicates.
By reversing this it would load the newest one and detect the old ones as duplicate.
Tested this and it works fine, no issues.
> PluginManager: Load plugins in reversed order.

- runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
At the moment it has 1 boolean value which means if you disable a plugin which needs it all other plugins which need it aswell will stop comparing.
With this it will keep an integer of the amount of plugins, and when it bocomes 0 it will stop comparing.
> RSClientMixin: Fix multiple plugins with comparing.

- runelite-client/src/main/java/net/runelite/client/RuneLite.java
Setting world through CLI was throwing the following exception:
`2020-12-31 11:42:09 [main] ERROR net.runelite.client.RuneLite - Uncaught exception:
mg: null
at fj.v(UserComparator9.java:103)
at ib.o(AbstractArchive.java:370)
at at.t(class51.java:125)
at bw.c(SecureRandomCallable.java:1504)
at client.changeWorld(Client.java)
at net.runelite.client.RuneLite.setWorld(RuneLite.java:590)
at java.base/java.util.Optional.ifPresent(Optional.java:183)
at net.runelite.client.RuneLite.start(RuneLite.java:536)
at net.runelite.client.RuneLite.main(RuneLite.java:433)`
Judging by the stack trace I'm assuming it's related to the client not being fully loaded yet before trying to set the world.
Moving RuneLite#setWorld to the end of RuneLite#start fixed this issue.
> runelite-client: Fix CLI world

- runelite-api/src/main/java/net/runelite/api/AbstractArchive.java
- runescape-api/src/main/java/net/runelite/rs/api/RSAbstractArchive.java
These methods are handy if you need to read cache files in a plugin.
> client: Added AbstractArchive runelite api file

- runelite-client/src/main/java/com/openosrs/client/OpenOSRS.java
- runelite-client/src/main/java/net/runelite/client/plugins/OPRSExternalPluginManager.java
- runelite-client/src/main/resources/openosrs.properties
setSystemVersion for PF4J is used to determine if an external plugin can be loaded without API mismatches. The name can be kinda misleading. Bumping this version every client update causes externals not to work until they have been recompiled against the latest client version even if the API hasn't changed.
This version follows the SEMVER standard and we should keep this in mind from now on when pushing out new client releases.
Given a version number MAJOR.MINOR.PATCH, increment the:
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
> client: Seperate system and api version

- runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
This disables sending / receiving configs from RuneLite servers.
It should however retain the ability of having profiles per user, so I would appreciate someone testing that.
> client: disable runelite config sync, keep profiles

- runelite-mixins/src/main/java/net/runelite/mixins/RSProjectileMixin.java
Fixed bug where Projectile.getInteracting() returns local player if the projectile is targeting a Player that the local player is interacting with.
It should return that Player instead of the local player.
> api: Bug fix of getInteracting() in Projectile mixin

- runelite-api/src/main/java/net/runelite/api/events/HealthBarUpdated.java
- runelite-mixins/src/main/java/net/runelite/mixins/RSActorMixin.java
Adds the HealthBarUpdated event and changes to support the event in RSActorMixin.
Getting the healthbar ratio in onHitsplatApplied results in the old healthbar ratio being used since the healthbar hasn't been updated yet from the hitsplat.
> api: adds HealthBarUpdated event and the corresponding mixin

- runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
https://github.com/runelite/runelite/commit/02025f9d8ffe378fa24e2df0a2058d6407bda3cc is pretty fucking useless without it.......
without, if you assign a double configItem type, the values don't display.
with this, they display, although the up + down arrows only work for xx. instead of .xx (can still manually amend)
> configpanel: double support

- runelite-api/src/main/java/net/runelite/api/Client.java
- runelite-mixins/src/main/java/net/runelite/mixins/MinimapMixin.java
Lets plugins disable the implementation of checkIfMinimapClicked
This is useful for plugins that add custom menu entries, which otherwise
would trigger in addition to a minimap click
> mixins: Add setMinimapReceivesClicks

- runelite-client/src/main/java/net/runelite/client/ui/overlay/Overlay.java
- runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
This is helpful for plugins that wish to show overlays that perform
actions when they have mouse focus, such as offering left click actions.
While it's possible to track this within the overlay itself it is difficult
to do correctly when considering overlapping overlays and overlays being
removed while they have focus.
> client: Make overlays aware of mouse focus

- runelite-mixins/src/main/java/net/runelite/mixins/RSGameObjectMixin.java
- runescape-api/src/main/java/net/runelite/rs/api/RSGameObject.java
java.lang.AbstractMethodError: Receiver class hf does not define or inherit an implementation of the resolved method 'abstract int getModelOrientation()' of interface net.runelite.api.GameObject.
at net.runelite.client.ui.overlay.outline.ModelOutlineRenderer.drawOutline(ModelOutlineRenderer.java:1028)
at net.runelite.client.ui.overlay.outline.ModelOutlineRenderer.drawOutline(ModelOutlineRenderer.java:1155)
at net.runelite.client.plugins.objectindicators.ObjectIndicatorsOverlay.render(ObjectIndicatorsOverlay.java:107)
at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:773)
at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:271)
at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:205)
at …
> api: rename getRsOrientation -> getModelOrientation inline with upstream

- runelite-client/src/main/java/net/runelite/client/account/SessionManager.java
This resolves config resets when using the Account plugin.
> client: use default config always

- runelite-api/src/main/java/net/runelite/api/Tile.java
- runelite-api/src/main/java/net/runelite/api/coords/WorldPoint.java
- runelite-mixins/src/main/java/net/runelite/mixins/RSTileMixin.java
1) Determine the checkpoint tiles of a server-sided path from this WorldPoint to another WorldPoint.
The checkpoint tiles of a path are the "corner tiles" of a path and determine the path completely. 
Note that true server-sided pathfinding uses collisiondata of the 128x128 area around this WorldPoint, while the client only has access to collisiondata within the 104x104 loaded area. This means that the results would differ in case the server's path goes near (or over) the border of the loaded area.
2) Determine the distance of the server-sided path between 2 tiles.
> api: Add pathfinding api

- buildSrc/src/main/kotlin/Dependencies.kt
- runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
newly compiled plugin-hub plugins use `getConfiguration(String groupName, String key, Type clazz)` and not `getConfiguration(String groupName, String key, Class<T> clazz)`
this temp fix prevents plugins from crashing your client, should be removed once OPRS complete the config merge
> configmanager: temp fix to prevent plugin-hub crashes

- runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
Looks like this part was forgotten when merging the [new menu entry api](https://github.com/open-osrs/runelite/commit/a42c845ad3c7cd64b1c738134b3dd874b83716d6#diff-42fdba36fa93bd0601d7e7acb5dc38d3b95f58bdcb4b141b72c504255fa61ccbL865)
> client: update menu entries that were modified by the MenuEntryAdded event

- runelite-client/src/main/java/net/runelite/client/util/HotkeyListener.java
If you look at upstream you can see our behaviour is drastically different. It results in the hotkey released event being double fired.
> client: fix hotkey listener double firing hotkey released event

- runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
Dunno why enumSet and enum were being converted to strings to check contains. It resulted in a bug where other enums could get toggled if their names were contained in the enumset string due to an enum name being a substring of another enum name.
> client: Fix enumset config panel

- runelite-api/src/main/java/net/runelite/api/Client.java
- runelite-mixins/src/main/java/net/runelite/mixins/LoginScreenMixin.java
Expose methods to specifically control part of the update cycle of the login screen. From a high level point of view this is no different than setLoginScreen(SpritePixels pixels) however the gamestate change is quite heavy and unnecessary when setting the login screen background every frame. Using setLoginScreen(SpritePixels pixels) for video playback results in some stutter for me.
I need this for a plugin that plays a video on the login screen but I understand if this is too specific to be included in the project.
> api: Add low level control methods for the login screen background

- deobfuscator/src/main/java/net/runelite/deob/updater/AnnotationAdder.java
When running the UpdateMappings gradle task this produces tons of spam output, which is already succinctly summarized at the end of its run by `log.info("Changed {} classes, {} methods, {} fields", impl, meth, field)`.
> project: Silent Annotation Adder

- runelite-api/src/main/java/net/runelite/api/overlay/OverlayIndex.java
- runelite-mixins/src/main/java/net/runelite/mixins/RSAbstractArchiveMixin.java
Useful for modifying the byte arrays from cache when requested by the client. This can be easily applied to load custom cache compatible files such as rs2 models (for runtime model replacing).
> client: Cache Overlay Mixin Addition

- runelite-client/src/main/java/net/runelite/client/plugins/openosrs/externals/ExternalPluginManagerPanel.java
If you have `Always on top` enabled on the client and the warning dialog appears behind the client then you get stuck where you can't minimize or interact with the client nor accept the warning dialog to close it.
> project: fix warning dialog
